### ISSUE TITLE
Terraform and hcl files in a directory with a symlink?

### ISSUE THREAD

**Issue by jcalvento** [gruntwork-io/terragrunt#1032]
I'd like to do something like this
```
root
|- commons
     | - *.tf
     | - *.hcl
|-dev
     | - parent.hcl
     | - symlink to commons
|-test
     | - parent.hcl
     | - symlink to commons
```
When I try running `terragrunt plan-all` it fails because can't find any terraform conf file (`Module /.../dev does not have an associated terraform configuration and will be skipped.`)

**Comment by yorinasub17** [comment]
This makes sense, because `terraform` isn't being called in `dev/commons`, but rather at `dev` and terraform doesn't automatically read the tf files when it is one directory under.

With that said, I am not 100% sure if symlinks would still work even if you pointed to `commons/main.tf` in `dev`. Terragrunt verbatim copies the files to the working directory (`.terragrunt-cache`, so I would expect the symlinks to be broken when it is copied over.

**Comment by jcalvento** [comment]
Ok, makes sense now. If I copy the commons dir before running the plan/apply it works properly so that must be the problem. Thanks!

**Comment by yorinasub17** [comment]
Thanks for closing the loop! Closing this issue now.
