### ISSUE TITLE
Terragrunt creates an s3 bucket with invalid KMS settings

### ISSUE THREAD

**Issue by cliveza** [gruntwork-io/terragrunt#1143]
When running `terragrunt plan` for the first time and accepting the the prompt to create an S3 bucket for the backend. The bucket is configured with a custom KMS key even though a `kms_key_id` is not specified.

```
$ terragrunt -v
terragrunt version v0.23.10
```

When you `terragrunt apply`, Terraform will create the resource but is not able to save the state file on s3

```
Failed to save state: failed to upload state: KMS.NotFoundException: Invalid keyId aws/s3
```

To fix this you have to manually edit the KMS properties for the bucket and either:

1.  Enter a valid custom KMS ARN, or
2. Change the dropdown from "Custom KMS ARN" to "aws/s3"

My main terragrunt.hcl has the following:

```
remote_state {
  backend = "s3"

  generate = {
    path = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }

  config = {
    region = "us-east-1"
    bucket = "some.bucket.somewhere"
    key    = "bob.tfstate"
  }
}
```

This screenshot shows what the bucket properties look like immediately after Terragrunt has created the bucket 
![image](https://user-images.githubusercontent.com/1900666/79488785-44b3dd80-7fe8-11ea-8de8-b7531c74e8b9.png)

**Comment by jfharden** [comment]
The KMS key aws/s3 doesn't exist until aws creates it automatically for you (so if you manually make any bucket and choose AWS-KMS that will also resolve this problem). Annoyingly you are not allowed to make keys which begin with the 'aws/' prefix through KMS so you can't create this yourself.

The configuration is set here: https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state_s3.go#L530

Possible options I can think of:
1. Instead of defaulting to `aws/s3` default to a terragrunt specific KMS key, and create it first if it doesn't exist
2. Check to see if aws/s3 KMS key exists, if not error with a helpful error message
3. Default the encryption to AES256

this: 
```
defEnc := &s3.ServerSideEncryptionByDefault{SSEAlgorithm: aws.String(s3.ServerSideEncryptionAes256)}
```

instead of:
```
defEnc := &s3.ServerSideEncryptionByDefault{KMSMasterKeyID: aws.String("aws/s3"), SSEAlgorithm: aws.String(s3.ServerSideEncryptionAwsKms)}
```

**Comment by jfharden** [comment]
If you are happy with any of those 3 options I can do a PR for it, I just hit this issue setting up a new repo against an account that is new

**Comment by brikis98** [comment]
> The configuration is set here: https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state_s3.go#L530

Ah, good find. It's unusual to refer to `aws/xxx` keys directly, as those are AWS-managed.

> Instead of defaulting to aws/s3 default to a terragrunt specific KMS key, and create it first if it doesn't exist

KMS master keys are $1/month each, and creating them requires specifying a number of IAM policies: e.g., you need to specify the admin, for if you don't, you lose all access to the master key (not even the root user can access it without explicit permissions). I don't think Terragrunt should be involved in creating new master keys at all.

> Check to see if aws/s3 KMS key exists, if not error with a helpful error message

It's supposed to be auto created when you first use it. Perhaps the way to do that with the Go SDK is to set `SSEAlgorithm` to KMS, but _not_ specify `KMSMasterKeyID`? Or does that lead to an error in the SDK? Not sure.

> Default the encryption to AES256

That also seems like a reasonable alternative... Though I'm guessing there will be immediate requests to have KMS support for at least some users... With the ability to specify a custom KMS key... 

> If you are happy with any of those 3 options I can do a PR for it, I just hit this issue setting up a new repo against an account that is new

Sure, thanks!

**Comment by jfharden** [comment]
> > Check to see if aws/s3 KMS key exists, if not error with a helpful error message
> 
> It's supposed to be auto created when you first use it. Perhaps the way to do that with the Go SDK is to set `SSEAlgorithm` to KMS, but _not_ specify `KMSMasterKeyID`? Or does that lead to an error in the SDK? Not sure.

This seems like the solution! According to the docs (https://aws.amazon.com/premiumsupport/knowledge-center/s3-object-encrpytion-keys/)

```To encrypt an object using the default aws/s3 CMK, define the encryption method as SSE-KMS during the upload, but don't specify a key:```

Removing the KMS Master Key ID does indeed work, as does setting it to the arn of the alias for the aws/s3 key instead of just the string `aws/s3` e.g.:

```
+       defEnc := &s3.ServerSideEncryptionByDefault{
+               KMSMasterKeyID: aws.String("arn:aws:kms:us-east-1:11111111:alias/aws/s3"),
+               SSEAlgorithm:   aws.String(s3.ServerSideEncryptionAwsKms),
+       }
```

I came across a different problem (while testing this) in the live example which maybe offers something to this problem too:

The default config in https://github.com/gruntwork-io/terragrunt-infrastructure-live-example/blob/master/terragrunt.hcl#L40 will cause:

1. Your state bucket to have default encryption of the aws KMS key aws/s3
2. Your actual state files to be encrypted using AES256 instead of the KMS key

This is becuse terragrunt generates the backend.tf with `encrypt=true`, but terraform, unless you specify kms_key_id as well will always use AES256 (see https://github.com/hashicorp/terraform/blob/master/backend/remote-state/s3/client.go#L163)

The live example could specify the KMS key id as well like:

```
remote_state {
  backend = "s3"
  config = {
    encrypt        = true
    kms_key_id     = "arn:aws:kms:${local.aws_region}:${local.account_id}:alias/aws/s3"
    bucket         = "${get_env("TG_BUCKET_PREFIX", "")}terragrunt-example-terraform-state-${local.account_name}-${local.aws_region}"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = local.aws_region
    dynamodb_table = "terraform-locks"
  }
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}
```

Returning to this repo..... you could, if the user has specified kms_key_id default their bucket to use that kms, otherwise fallback to aws/s3 and populate kms_key_id with the right arn before writing out the terraform backend.tf.

**Comment by swarren** [comment]
I believe I have an issue related to this; perhaps the same thing.

With terragrunt version v0.23.32, my backend bucket gets created with AWS-KMS default encryption, but an empty value for the key ID (as viewed in the console). This causes all S3 access log objects to be created with AWS-KMS encryption, but whenever I try to view the objects, using either the AWS console or AWS CLI, I get a permission denied error. Note: I get an expected 404 if I deliberately access a non-existent object ID, so this is not a general "you can't access the bucket" issue.

However, if I change the bucket configuration to AES256 manually via the console, subsequent access log objects are created with that encryption type, and I can view them using the console or CLI, with no other changes at all.

Is it possible to make TG configure the bucket for AES256 encryption rather than KMS? Are there any downsides to doing that?

**Comment by denis256** [comment]
Fix released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.37.0
