### ISSUE TITLE
Create multiple resources from same source module in terragrunt

### ISSUE THREAD

**Issue by adi4dpeople** [gruntwork-io/terragrunt#1156]
I couldn't find a more suitable issue to address my problem than this so I'm reopening this. I have a setup where i have environments folder living inside my modules directory and it structure is like below. Only the values inside .tfvars vary per environment but remaining all are duplicated. So I'm testing terragrunt currently. But, I couldn't find terragrunt documentation on how to create multiple resources from same source module.  If i start writing modules similar to what you have suggested to @jpreese, i would still end up duplicating the code because i will have a main.tf in which i call all the modules, different values for each modules so i need have vars.tf and finally i need to pass values through tfvars. So in my scenario how can I DRY my code?   

current environments directory structure. 
```
├── environments
│   ├── hub
│   │   ├── datasources.tf
│   │   ├── extract_tf_vars.py
│   │   ├── main.tf
│   │   ├── prod_hub.tfvars
│   │   ├── provider.tf
│   │   └── vars.tf
│   ├── perf
│   │   ├── datasources.tf
│   │   ├── extract_tf_vars.py
│   │   ├── main.tf
│   │   ├── perf.tfvars
│   │   ├── provider.tf
│   │   └── vars.tf
│   ├── prod
│   │   ├── datasources.tf
│   │   ├── extract_tf_vars.py
│   │   ├── main.tf
│   │   ├── prod.tfvars
│   │   ├── provider.tf
│   │   └── vars.tf
│   └── trng
│       ├── datasources.tf
│       ├── extract_tf_vars.py
│       ├── main.tf
│       ├── provider.tf
│       ├── trng.tfvars
│       └── vars.tf
```

Right now this is how I'm calling the modules from terragrunt. 
```
aditya@LAPTOP-6C2MPJDV:~$ cat terraform_live/perf/virtual_network/terragrunt.hcl
terraform {
  source = "git::git@github.com:adi4dpeople/terraform_modules.git//virtual_network?ref=v0.0.1"
}

# Include all settings from the root terragrunt.hcl file
include {
  path = find_in_parent_folders()
}

dependency "resource_group" {
  config_path = "../resource_group"
}

# These are the variables we have to pass in to use the module specified in the terragrunt configuration above
inputs = {
  vnet_name = "testvnet"
  vnet_address_space = "1.2.3.4/16"
  resource_group_name = dependency.resource_group.outputs.name
}
```

_Originally posted by @adi4dpeople in https://github.com/gruntwork-io/terragrunt/issues/781#issuecomment-620747921_

**Comment by yorinasub17** [comment]
If I understand what you want correctly, you are basically looking for a way to call modules with `for_each`. If so, this is not something we plan on supporting in terragrunt.

See https://github.com/gruntwork-io/terragrunt/blob/master/_docs/rfc/for_each_iteration.md for more details on why.

**Comment by adi4dpeople** [comment]
@yorinasub17 thanks for the response. I'm not quite sure if I need to use a for_each loop. I can use multiple module {} blocks in the same main.tf because i consider code is much cleaner and gives the capability to pass different types of properties for the same module as in the example given below. 

But my code is duplicated when I copy and paste the same main.tf file from dev to all the other environments. Only the values passed to the modules are different per environment. 

I'm looking for a solution like this:
A single main.tf or terragrunt.hcl (whatever be the filename) for all the environments in which the values passed to modules can change dynamically based on the environment. 

```
module "mgmt_nsg" {
  source              = "git::git@github.com:adi4dpeople/terraform_modules.git//nsg?ref=v0.0.1"
  nsg_name            = var.mgmt_nsg_name
  location            = var.location
  resource_group_name = module.resource_group.name
}

module "shr_subnet" {
  source               = "git::git::git@github.com:adi4dpeople/terraform_modules.git//nsg?ref=v0.0.1"
  subnet_name          = var.shr_subnet_name
  resource_group_name  = module.resource_group.name
  vnet_name            = module.virtual_network.name
  subnet_address_space = [var.subnet_address_prefixes[1]]
 route_table_id            = module.fw_route_table.id[0]
}
```

**Comment by yorinasub17** [comment]
I think I am having difficulty understanding your constraints. Why can't you create a terraform module in your repo that does exactly what you are doing, have terragrunt point to that module in the source param and adjust the inputs by environment? I guess I am having trouble understanding why you also have `main.tf` in your live config.

FWIW, I think https://github.com/gruntwork-io/terragrunt/issues/759 is what you are looking for, but this will take a long time before we are ready to implement.

**Comment by adi4dpeople** [comment]
@yorinasub17, sorry if i was not clear. As you have suggested, I have a terragrunt.hcl file inside my /terraform_live/perf/resource_group which calls my modules. 

The variables in my resource_group module are rg_name and location so I'm passing them inside inputs {} block. 

You are right that i can create different resource groups in each environment using separate terragrunt.hcl file. 

But if i want to create more than one resource group in the same environment, then this approach is not working. Please advise on this. 

```
terraform {
  source = "git::git@github.com:adi4dpeople/terraform_modules.git//resource_group?ref=v0.0.1"
}

# Include all settings from the root terragrunt.hcl file
include {
  path = find_in_parent_folders()
}

# These are the variables we have to pass in to use the module specified in the terragrunt configuration above
inputs = {
  rg_name  = "jenkinsrg01"
  location.   = "westus"
}
```

**Comment by adi4dpeople** [comment]
If there is no way to achieve the above through terragrunt, please let me know the best practice for such scenarios.

**Comment by yorinasub17** [comment]
The main model of Terragrunt is to define service modules that define a blueprint for your resources. This should be the common components across your environments. E.g., you might have a service definition for your VPC architecture, and another one for your RDS databases.

Each of these service modules are terraform modules that you can deploy at the top level, which you then configure for each environment via just the variables. Terragrunt helps DRY up the variable calls by not having to duplicate the variables and outputs of terraform.

This architecture helps keep terragrunt lightweight in implementation, and take advantage of the features of terraform for what it is good at.

Given that, it sounds like what you want to accomplish is to dynamically pick and choose which modules to include in your environment. There are three options here:

- Define a service wrapper module for each group that needs to be stamped out. This works best if there is a common resource set for each environment. If it is truly dynamic across all your environments, then this may not be the best approach.
- Dynamically compose the environment resources using separate modules. That is, anything that is optionally added into an environment should be a separate terragrunt configuration. So instead of combining your resources into a common module, you have multiple modules that are independently turned on and off by the existence of a terragrunt config to deploy it.
- Use terraform directly. You may have enough differences in your resource composition that there is just no way to DRY it up cleanly. This is a sign that these are truly different terraform modules and may not be necessary to add `terragrunt`.

---

So to be more specific, when you need another resource group you can either define a new terraform module and terragrunt call, or replicate the folder structure to for the new resources to call the module again using different parameters.

FWIW, we have had some people in the community also use templating and codegen to introduce further DRY-ness, as mentioned in the for_each RFC, although that adds further abstractions and complications to the point that it isn't really recommended.

**Comment by adi4dpeople** [comment]
@yorinasub17 thank you. It seems the best way forward is to create separate folders for each same type of module I'm calling from terragrunt. With this model, i reduce the duplicates and resources are isolated which enables me to apply changes independently. 

```
NIST-MAC-L-0032:perf aambati$ tree
.
|-- resource_group
|   `-- terragrunt.hcl
|-- resource_group01
|   `-- terragrunt.hcl
`-- virtual_network
    `-- terragrunt.hcl
```

**Comment by dtcMLOps** [comment]
> @yorinasub17 thank you. It seems the best way forward is to create separate folders for each same type of module I'm calling from terragrunt. With this model, i reduce the duplicates and resources are isolated which enables me to apply changes independently.
> 
> ```
> NIST-MAC-L-0032:perf aambati$ tree
> .
> |-- resource_group
> |   `-- terragrunt.hcl
> |-- resource_group01
> |   `-- terragrunt.hcl
> `-- virtual_network
>     `-- terragrunt.hcl
> ```

@aditya-ambati I am having the same requirement for my terragrunt files and there is not a clean way to implement this. I will follow your approach
