### ISSUE TITLE
prevent-destroy error when destroying should instead be a warning that the flag is enabled

### ISSUE THREAD

**Issue by jgfincore** [gruntwork-io/terragrunt#1221]
When doing a destroy-all on a group of modules, one or more which may have the 'prevent_destroy = true' flag enabled, it will exit with an error code of 1 and the following error:

Encountered the following errors:
Module is protected by the prevent_destroy flag in terragrunt.hcl. Set it to false or delete it to allow destroying of the module.

Should this not be a warning rather than an error?

**Comment by brikis98** [comment]
Hm, that's a good question. Currently, [it is an error](https://github.com/gruntwork-io/terragrunt/blob/48d76941e192173c0e0df3caeeaf21906035e63e/cli/cli_app.go#L887-L889), which has the advantage of making sure you see that the destroy failed, and don't think it went through successfully just because you got an exit code of 0. However, as you pointed out, the drawback is that when using it with `destroy-all`, there are cases where you want it to fail to destroy, and don't want that to be an error.

I suppose a solution could be to add a `--terragrunt-warn-on-prevent-destroy` flag and/or `warn_on_prevent_destroy` setting in `terragrunt.hcl`, that, if set, turns this error into a warning instead. However, I also worry about adding so many options and flags, so I'd want to be sure this is a common use case. @yorinasub17 Would be curious to hear your thoughts.

Also, a potential workaround is to use `--terragrunt-exclude-dir` and/or `--terragrunt-include-dir` to exclude dirs with `prevent_destroy` from your `destroy-all` command.

**Comment by jgfincore** [comment]
Good idea!   `--terragrunt-warn-on-prevent-destroy` flag would be a very tidy solution!   We use a Makefile so including the one flag rather than including/excluding modules would make for a nicer flow.

**Comment by yorinasub17** [comment]
I'd like to hear more about the use case and more specifically the folder structure of the infra.

Personally, it feels like a smell if there is a workflow that runs `destroy-all` regularly with modules that contain `prevent_destroy = true`. It seems safer to reorganize your folder structure so that the modules you don't want destroyed are not included.

**Comment by jgfincore** [comment]
The structure is similar to below.  We use a Makefile to handle all plan/-all, apply/-all, etc.   
Lets take the api modules for example.  During development where I might be doing a fair bit of plan/apply/destroy, I don't necessarily want to keep enabling/disabling APIs on GCP.  I drop a prevent-destroy flag in the api module's terragrunt.hcl file and then it is safe from being destroyed.  This is handy and saves me time.  I do the same for other modules as well.  

Its nice to be able to say, work on the gke module and be able to build/destroy it and those modules that come after it without having to destroy the few that come before it.  

I guess the question is, if I set prevent_destroy, should it be considered an error at the end of the run?  It's obviously good to have some notice that its set, but a warning rather than an error seems appropriate.   

gcp
├── dev
│   ├── accounts.hcl
│   ├── api
│   │   └── terragrunt.hcl
│   ├── common.hcl
│   ├── compute
│   │   └── admin
│   │       └── terragrunt.hcl
│   ├── env.hcl
│   ├── gke
│   │   └── terragrunt.hcl
│   ├── iam
│   │   └── projects
│   │       └── terragrunt.hcl
│   ├── network
│   │   ├── cloudnat
│   │   │   └── terragrunt.hcl
│   │   ├── subnets
│   │   │   └── terragrunt.hcl
│   │   └── vpc
│   │       └── terragrunt.hcl
│   └── app
│       └── terragrunt.hcl
├── prod
└── terragrunt.hcl

**Comment by yorinasub17** [comment]
Thanks for sharing your folder structure and use case! Interactive development using `prevent_destroy` is something I hadn't thought about, but makes perfect sense.

In that case, I think it is fairly reasonable to introduce a `--terragrunt-warn-on-prevent-destroy` CLI flag, but probably not a `warn_on_prevent_destroy` attribute in the config file.

> I guess the question is, if I set prevent_destroy, should it be considered an error at the end of the run?

I think it should be an error by default, in the sense that you requested to destroy infrastructure but terragrunt couldn't destroy that infrastructure. This will also help when we have better error aggregation in the future for `xxx-all` commands, as that enables these to show up at the end in an error summary view.
