### ISSUE TITLE
terragrunt version string is different when installed using brew

### ISSUE THREAD

**Issue by arjunurs** [gruntwork-io/terragrunt#123]
Version string when using official binary is `terragrunt version v0.9.8`. When I install the binary from brew the version string is `terragrunt version 0.9.8`. It's a minor difference but it might be a simple fix.

**Comment by brikis98** [comment]
Looks like the [HomeBrew formula for Terragrunt](https://github.com/Homebrew/homebrew-core/blob/1dc96a2d27cf30b8dae801334b49095dfcb7010c/Formula/terragrunt.rb) rebuilds the binary from source rather than using the ones uploaded to the GitHub releases page. The build process is where the version number gets baked in, so I'm guessing the formula just needs to prepend the `v`. 

Should this be a bug in the Homebrew repo instead? Anyone up for a PR? @josh-padnick, thoughts?

**Comment by josh-padnick** [comment]
I threw that Formula together one day pretty quickly versus comprehensively researching it. I agree with @brikis98 that [this line](https://github.com/Homebrew/homebrew-core/blob/1dc96a2d27cf30b8dae801334b49095dfcb7010c/Formula/terragrunt.rb#L25) needs to be updated to:

```ruby
# Note the added "v" after VERSION= 
system "go", "build", "-o", bin/"terragrunt", "-ldflags", "-X main.VERSION=v" + version.to_s
```

@arjunurs Interested in making that change?

Also, my understanding is that homebrew [prefers](http://docs.brew.sh/Acceptable-Formulae.html) build vs. download.

**Comment by arjunurs** [comment]
@josh-padnick sure, I'll make the change in homebrew repo. Thanks for providing the information.

**Comment by josh-padnick** [comment]
@arjunurs Happy to help!
