### ISSUE TITLE
find_in_parent_folders documentation and tfvars files

### ISSUE THREAD

**Issue by fitzoh** [gruntwork-io/terragrunt#1238]
The [find_in_parent_folders documentation](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#find_in_parent_folders) has an example that implies terragrunt configuration can be read from `tfvars` files.

This seems to be the only reference to reading from non-hcl files, and is not explained.

Is this an error in the documentation, or is there a way to store terragrunt configuration in `tfvars` files?

<img width="847" alt="Screen Shot 2020-06-27 at 3 47 12 PM" src="https://user-images.githubusercontent.com/131809/85930844-92bd4b00-b88d-11ea-92b4-ea7d626e0278.png">

**Comment by yorinasub17** [comment]
Good catch! This is an error in the docs. Terragrunt 0.18 and older used `tfvars` files for its configuration, but with terraform 0.12 we had to update to using hcl files since `tfvars` files no longer allowed extra variables to be defined.

Fixed this in https://github.com/gruntwork-io/terragrunt/pull/1239
