### ISSUE TITLE
Running before_hook to login into AWS account

### ISSUE THREAD

**Issue by luizm** [gruntwork-io/terragrunt#1256]
Hi there

When I configure the `before_hook` parameter, it will be run before terraform command, but its always run after terragrunt try to load the config such as bucket where are located the tfstates.

I've tried to use use `before_hook` to run a specific command that configures my profile using an AWS temporary credentials

For instance:

```
  before_hook "login_aws" {
    commands = ["apply", "plan"]
    execute  = ["<my-custom-cli>", "aws", "login", "<profile-name>"]
  }
```

I failed to figure out by myself if there is another way to do that or if its a good idea to add a terragrunt.

Thank you

**Comment by yorinasub17** [comment]
I don't think this is possible due to the same reason as https://github.com/gruntwork-io/terragrunt/issues/1236#issuecomment-650691433 .

With that said, I think there is a clever thing you can do with [run_cmd](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#run_cmd), which runs external commands while terragrunt is parsing the config (unlike the hooks, which can only run after parsing is done).

**Comment by luizm** [comment]
> I don't think this is possible due to the same reason as [#1236 (comment)](https://github.com/gruntwork-io/terragrunt/issues/1236#issuecomment-650691433) .

> I don't think this is possible due to the same reason as #1236 (comment) .

In my case I don't wanna set an env, I would like to run a command before terragrunt try to get and use the secrets from aws profiles.

> With that said, I think there is a clever thing you can do with run_cmd, which runs external commands while terragrunt is parsing the config (unlike the hooks, which can only run after parsing is done).

Nice, I will take a look in the `run_cmd`parameter, thank you @yagnamanirudh
