### ISSUE TITLE
terragrunt running within a container is killed without error

### ISSUE THREAD

**Issue by oferzi23** [gruntwork-io/terragrunt#1292]
i have a strange issue where i run terragrunt inside a container. after building and running the container i can plan and apply just fine but after some time terragrunt starts failing without any error beside `Killed` in the terminal. restarting the container fixes the issue but as i plan to start using this container for automation, it might cause some issues.

i tried to export `TF_LOG=DEBUG` but still no output which leads me to understand the command is never passed into terraform and is killed before the tf binary execution. also tried running the command with `--terragrunt-debug` and still nothing... will appreciate some direction on how to debug this. thanks

**Comment by yorinasub17** [comment]
`Killed` indicates that some OS process is killing the process (perhaps OOM? or stdout buffer limits?). When there is a fatal error caused by terragrunt or terraform itself, you should get a panic log and traceback.

I would look into monitoring the container resource usage as terragrunt runs to see if there are resource issues (see [docker container top](https://docs.docker.com/engine/reference/commandline/container_top/) and [docker container stats](https://docs.docker.com/engine/reference/commandline/container_stats/)).

The most likely cause of this that I have seen in the past is if you have a really long plan line (e.g., injecting json/text data where a single line is above the buffer limits that terragrunt uses). Do you have anything like that in your modules?

**Comment by oferzi23** [comment]
not something i know of, and i get this error for modules which for sure do not have anything like that.
the contianer does not exit so i don't think it's a container resource limit issue...where should i see these panic / trace logs?

**Comment by yorinasub17** [comment]
The panic trace logs should show up in stdout and stderr where terragrunt is running.

**Comment by yorinasub17** [comment]
Closing as stale. If this is still an issue, please open a follow up ticket with updated context. To get more verbose logs, you can probably do `--terragrunt-log-level debug`. Note that it would also help if we can get the `Dockerfile` and a sample project to see if we can reproduce the issue. Thanks!
