### ISSUE TITLE
terragrunt ignores --terragrunt-config / TERRAGRUNT_CONFIG files

### ISSUE THREAD

**Issue by tmclaugh** [gruntwork-io/terragrunt#130]
contrary to docs, terragrunt ignores --terragrunt-config arg, TERRAGRUNT_CONFIG env var, and .terragrunt file when looking for tfvars.  terragrunt will fail of the given file does not exist but it does not appear to read the file.  I'm currently working around this by symlinking terraform.tfvars back to the tfvars file I want.  This does not work long term for me as I'm trying to drive different environments entirely by separate tfvars files.

Ignored given file:
```
[tmclaughlin@tomcat-ts:aws-straycat straycat-terraform-aws-vpc(modularize)*]$ terragrunt plan --terragrunt-config straycat.tfvars
[terragrunt] 2017/02/16 10:17:06 Reading Terragrunt config file at straycat.tfvars
[terragrunt] 2017/02/16 10:17:06 Remote state is already configured for backend s3
[terragrunt] 2017/02/16 10:17:06 WARNING: you have not configured locking in your Terragrunt configuration. Concurrent changes to your .tfstate files may cause conflicts!
[terragrunt] 2017/02/16 10:17:06 Running command: terraform plan
var.aws_account
  Enter a value: ^C
Error configuring: Error asking for aws_account: interrupted

[tmclaughlin@tomcat-ts:aws-straycat straycat-terraform-aws-vpc(modularize)*]$ ls -al straycat.tfvars
-rw-r--r--  1 tmclaughlin  staff  789 Feb 15 17:25 straycat.tfvars
```

Failed on non-existent file:
```
[tmclaughlin@tomcat-ts:aws-straycat straycat-terraform-aws-vpc(modularize)*]$ terragrunt plan --terragrunt-config doesnotexist.tfvars
[terragrunt] 2017/02/16 10:18:26 Reading Terragrunt config file at doesnotexist.tfvars
Error reading file at path doesnotexist.tfvars: open doesnotexist.tfvars: no such file or directory
[terragrunt] 2017/02/16 10:18:26 Error reading file at path doesnotexist.tfvars: open doesnotexist.tfvars: no such file or directory
```

**Comment by brikis98** [comment]
```
[terragrunt] 2017/02/16 10:17:06 Reading Terragrunt config file at straycat.tfvars
[terragrunt] 2017/02/16 10:17:06 Remote state is already configured for backend s3
[terragrunt] 2017/02/16 10:17:06 WARNING: you have not configured locking in your Terragrunt configuration. Concurrent changes to your .tfstate files may cause conflicts!
[terragrunt] 2017/02/16 10:17:06 Running command: terraform plan
var.aws_account
  Enter a value:
```

This looks to me like *Terragrunt* is using the `straycat.tfvars` (as it says in the log output), but *Terraform* is not, which is why you are being asked to enter the `aws_account` variable. This is expected. Terragrunt and its `--terragrunt-XXX` arguments do NOT affect which variables and variable files Terraform reads in. Therefore, the variables that are going to be visible to Terraform will be exactly the same as if you ran `terraform plan`. 

By default, Terraform looks for variables in the following places:

* `default` values in the `variable` definition.
* `TF_VAR_XXX` environment variables.
* `-var` arguments.
* `-var-file` arguments.
* `terraform.tfvars`. 
* `terraform.tfvars.json`.

Notice how `straycat.tfvars` is not in that list. If you want Terraform to read variables from it, use the `-var-file` flag:

```
terragrunt plan --terragrunt-config straycat.tfvars --var-file straycat.tfvars
```

I admit this may be confusing, so I'd welcome a PR to update the docs to clarify the role of the `--terragrunt-config` flag and help others avoid this confusion in the future :)

**Comment by tmclaugh** [comment]
Yes!  Okay, I had assumed the --terragrunt-config would affect --var-file.  Let me shoot a PR later.

**Comment by brikis98** [comment]
Great, thanks!
