### ISSUE TITLE
Is .terragrunt-cache an anti-pattern?

### ISSUE THREAD

**Issue by dhoer** [gruntwork-io/terragrunt#1325]
I find it interesting that terragrunt is focused on keeping it DRY but cache is anything but DRY.  I find it frustrating that a specific version of a provider is downloaded repeatedly for each module.   Am I using terragrunt incorrectly?

I would think that cache would:
1. Write only one .terraform-cache file at top level and mirror dir structure under it.  This would eliminate the need to explain how to remove the multiple cache directories.
2. Download modules and providers once, under .terraform-cache/modules and .terraform-cache/providers accordingly since they are versioned (git with no version would use first 8 chars of git hash). Then copy from there to appropriate sub-directory.
3. Allow to change directory location from within terragrunt.hcl. I don't want to configure an environment variable, just set the value like I would with terraform vars.

This would cut down the number of cache directories and drastically reduce the cost of downloading the same modules and providers over and over again.  Especially if network is slow.

**Comment by james-gonzalez** [comment]
I think it's fair to say that quite a few of "us" have to put in workarounds(i.e. - deleting `.terragrunt-cache`) to deal with the potential issues that `terragrunt-cache` may cause.


Described here:
https://terragrunt.gruntwork.io/docs/features/caching/

**Comment by brikis98** [comment]
The thing to remember is that Terraform, not Terragrunt, is what's downloading providers, plugins, and modules. If you were using multiple Terraform modules, with no Terragrunt involved at all, it would still be downloading the modules and providers multiple times. Terraform does allow you to cache providers to avoid downloading those over and over again: see [`plugin_cache_dir` in these docs](https://www.terraform.io/docs/commands/cli-config.html), so I recommend enabling that if you can.

> I find it interesting that terragrunt is focused on keeping it DRY but cache is anything but DRY. I find it frustrating that a specific version of a provider is downloaded repeatedly for each module. Am I using terragrunt incorrectly?

To be fair, DRY is mostly a concept applied to the code you write/maintain. Not to artifacts downloaded during execution or anything like that. That's like saying Java code isn't DRY because the compiled bytecode may have duplication in it. It's just not relevant.

That said, I understand your frustration with extra downloads slowing down deployments and eating up disk space. For now, the best option is using `plugin_cache_dir` as mentioned above.

> 1. Write only one .terraform-cache file at top level and mirror dir structure under it.  This would eliminate the need to explain how to remove the multiple cache directories.
> 2. Download modules and providers once, under .terraform-cache/modules and .terraform-cache/providers accordingly since they are versioned (git with no version would use first 8 chars of git hash). Then copy from there to appropriate sub-directory.

I assume you mean `.terragrunt-cache`? If so, a few thoughts:

1. What is the "top level?" Not all Terragrunt users structure their projects the same way. If you mean it's the folder where the "parent" `terragrunt.hcl` is defined—the one used in `include`—bear in mind that not everyone uses `include`.
1. Terragrunt only uses `.terragrunt-cache` as a "download dir" when you specify a `source` of some Terraform configuration you want to download. It downloads the module you specify at `source` into `.terragrunt-cache/xxx/<module>` and then copies the files you have in the current working dir (e.g., `.tfvars` files) into `.terragrunt-cache/xxx/<module>` as well. If we had a single top-level `.terragrunt-cache`, these copied files would likely overwrite each other, causing errors (especially as part of `apply-all`).
1. Part of the reason `.terragrunt-cache` is a "cache" is that it has some logic to avoid having to download the same code multiple times. E.g., if you're running multiple commands on the same module (e.g., first `plan`, then `apply`, then `output`), the code (and modules, providers, backend, etc) only have to be initialized the very first time for that module. If we had a single top-level `.terragrunt-cache` that tried to mix all modules, we'd have to do more thinking about what could and couldn't be cached, how to make this work with concurrency (e.g., during `apply-all`), and other complicating factors.

The issues mentioned above can probably be solved, but it would probably take a fair amount of thought about how to make it work correctly. If you'd be interested in improving this, [an RFC](https://terragrunt.gruntwork.io/docs/rfc/template/) is very welcome.

> 3. Allow to change directory location from within terragrunt.hcl. I don't want to configure an environment variable, just set the value like I would with terraform vars.

Change the directory location of the download dir? If so, you already can set it in `terragrunt.hcl` and via CLI and env var:

https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#download_dir
https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-download-dir

> This would cut down the number of cache directories and drastically reduce the cost of downloading the same modules and providers over and over again. Especially if network is slow.

Again, remember that Terragrunt is not what does the downloading of providers or the modules specified by `module`; it's Terraform. So without modifying the internals of Terraform itself, this is harder than it sounds!

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!

**Comment by tuananh** [comment]
now that we have opentofu, we can optimize this now?

**Comment by jullianow** [comment]
@tuananh https://terragrunt.gruntwork.io/docs/features/provider-cache/

**Comment by yhakbar** [comment]
Also note that the OpenTofu folks are interested in addressing this on the OpenTofu side as well:
https://github.com/opentofu/opentofu/issues/1483
