### ISSUE TITLE
Where can I find the supported versions of Terraform for each Terragrunt release?

### ISSUE THREAD

**Issue by miiitch** [gruntwork-io/terragrunt#1359]
This list is usefull to keep terragrunt and terraform compatible at all time.

**Comment by yorinasub17** [comment]
We never really documented this because the answer is more complicated than a simple table.

Terragrunt officially supports 0.12.x with 0.19 - 0.25, and 0.11.x with 0.18.

But this just means that we are/have tested those versions against those terragrunt releases. For example, 0.13.x is known to work with any version above 0.19 in the community. We also know that tf11 works with 0.19+, but requires setting [terraform_version_constraint](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform_version_constraint).

So it's not really cut in stone which versions work with which release.

**Comment by brikis98** [comment]
#1362 added a version compatibility table, which you can find at: https://terragrunt.gruntwork.io/docs/getting-started/supported-terraform-versions/
