### ISSUE TITLE
Unable to fetch output from terragrunt hcl --> .cache --> autogenerated folder name --> module --> output.tf file in terratest Golang using terraform.Output(t,terraformOptions,variableName) function

### ISSUE THREAD

**Issue by pandu-bhojaraj-mf** [gruntwork-io/terragrunt#1410]
I am **able** to initialize and apply terragrunt files from terratest Golang using **terraform.TgApplyAll(t, terraformOptions)**

But when i use below piece of code , I am unable to fetch value of output variable(s3_bucket_name)

**s3BucketName := terraform.Output(t, terraformOptions, "s3_bucket_name")**

Getting below warning message

_Warning: No outputs found\n\nThe state file either has no outputs defined, or all the defined outputs are\n empty. Please define an output in your configuration with the output keyword\n and run terraform refresh for it to become available. If you are using\n interpolation, please verify the interpolated value is not empty. You can use\nthe terraform console command to assist."_

**Same code is working fine for terraform but not working for terragrunt**
 
But i am able to see output in Command line after running suit

In terraform, output.tf file is present under module
In terragrunt, output.tf file is present under .cache -->some autogenerated folder name --> module name -->output.tf

**To fetch the output from terratest Golang , Do we need to follow any different steps for terragrunt as compare to terraform ?**

@brikis98 @yorinasub17  @mcalhoun  @conorgil  Please help

**Comment by yorinasub17** [comment]
It's a bit hard to debug this without seeing your folder structure and `terragrunt.hcl` code, but my best guess is that you have the `TerraformDir` misconfigured such that it is running `terragrunt output` in the wrong directory. This is based on your usage of `apply-all`, which implies that you are running multiple modules at once.

Note that `output` only works off of a single module, so if you are using `terragrunt` to run multiple modules, then you need to make sure the `TerraformOptions` is updated to run `output` from the correct (single) terragrunt module folder.

**Comment by pandu-bhojaraj-mf** [comment]
Hi @yorinasub17 

Thanks for your response , Yes **I am running multiple modules at once** and TerraformDir  is pointing one parent folder under which multiple modules are present  , 

When I run "**terragrunt apply-all --terragrunt-non-interactive**" command then i am **able to see output** in command line
But I am not able to fetch same from terraform output function

Below is the piece of code which i have written for invoking terragrunt modules from terratest go lang

![image](https://user-images.githubusercontent.com/73541850/97897839-0e0f9b80-1d5d-11eb-96a3-db2605409447.png)

Here is the folder structure

![image](https://user-images.githubusercontent.com/73541850/97898361-c8070780-1d5d-11eb-815a-a7ef55255097.png)


with-infra is one folder under which 4 folders are present along with one terragrunt.hcl that has only input variables
Each of the folder from 4 has terragrunt.hcl and .cache will get generate after run which has 2 auto generated folder under which whole terraform code will load including maint.tf/output.tf etc..

My test script(terraform_aws_hello_world_example_test.go) is written under test folder,


So , To make it work 
Do i need to mention **TerraformDir** to individual module ?

**Comment by yorinasub17** [comment]
Yes you need to mention the `TerraformDir` to the individual module when extracting the outputs.

> When I run "terragrunt apply-all --terragrunt-non-interactive" command then i am able to see output in command line
But I am not able to fetch same from terraform output function

These outputs are not machine parseable. To get the machine parseable outputs so that we can turn them into golang variables, we need to run `terragrunt output -json` in the specific module (terragrunt doesn't support getting outputs from multiple modules).

**Comment by pandu-bhojaraj-mf** [comment]
Thank you @yorinasub17 , Its working with individual module

terraformOptions := &terraform.Options{
		TerraformDir:    "../with-infra/s3_bucket",
		TerraformBinary: "terragrunt",
	}

**Comment by pandubiet** [comment]
> Yes you need to mention the `TerraformDir` to the individual module when extracting the outputs.
> 
> > When I run "terragrunt apply-all --terragrunt-non-interactive" command then i am able to see output in command line
> > But I am not able to fetch same from terraform output function
> 
> These outputs are not machine parseable. To get the machine parseable outputs so that we can turn them into golang variables, we need to run `terragrunt output -json` in the specific module (terragrunt doesn't support getting outputs from multiple modules).

@yorinasub17 

Is this limitation still exist ?

I have a Project which will deploy multiple modules in one shot but unable to validate them using terratest due to this above concern 

Example  , I have a folder structure like below

![image](https://user-images.githubusercontent.com/53611343/103623228-d3450200-4f5d-11eb-88ad-7e834c1b8713.png)

When i run terragrunt apply-all with --terragrunt-include-external-dependencies command under with-infra-->vertica-cluster folder , then i can see VPC , S3 and vertica-cluster deployed sequentially and output also showed respectively ONE BY ONE 

![image](https://user-images.githubusercontent.com/53611343/103623419-25862300-4f5e-11eb-881d-16cdee8a84a7.png)

![image](https://user-images.githubusercontent.com/53611343/103623558-464e7880-4f5e-11eb-8639-52832d7a2976.png)

![image](https://user-images.githubusercontent.com/53611343/103623673-6b42eb80-4f5e-11eb-9965-04db3c1bb9c8.png)

But , When i try to fetch output of S3 or VPC , I am unable to get, Getting error as _The output variable requested could not be found in the state file_
I can only validate output of vertica-cluster which is **blocker for me from the perspective of validating output of all modules at one shot in single script(where as deployment**(terragrunt) supports still testing(terratest) doesn't supports)
Ex
I have some scenarios in a single flow , like , In our project EC2 user name will dynamically gets genrated from different module , so i need to read that as part of output in different module and need to use it for validating EC2 SSH connection
