### ISSUE TITLE
dependencies block is ignored

### ISSUE THREAD

**Issue by ahmad-hamade** [gruntwork-io/terragrunt#1415]
Looks like the `dependencies` block is never evaluated even if I give a wrong path it will continue to run.

I'm using terragrunt version v0.26.0

**Comment by yorinasub17** [comment]
This is sort of expected behavior as the `dependencies` block is only used for constructing the graph in `xxx-all` commands, but does not do any form of validation outside of type checks.

It would definitely be useful to do a folder existence check. We're a bit buried with other initiatives right now, but a PR is very welcome if anyone in the community wants to take a stab at it!

**Comment by brikis98** [comment]
@denis256 could you look into this one?
