### ISSUE TITLE
[Feature] mock_outputs encompass objects

### ISSUE THREAD

**Issue by bbros-dev** [gruntwork-io/terragrunt#1425]
TG: 0.25.1
TF: 0.13.4

When a variable has type `object`, and modules have dependencies, it is not possible to use `mock_outputs`:

```bash
Error: Invalid value for module argument on main.tf line 3, in module "label":
3:   context    = var.context
The given value is not suitable for child module variable "context" defined at
../terraform-null-label/variables.tf:1,1-19: object required.
```

Appreciate any hints, tips or workarounds.

**Comment by brikis98** [comment]
What value are you setting it to?

**Comment by bbros-dev** [comment]
We refactored everything to remove this, so from memory we tried `{...}`, `[..]`, `object()`, possibly others, but couldn't get past this.

The context might help - using Cloud Posse`s label module we wanted to pas its `context` attribute around.

**Comment by yorinasub17** [comment]
Closing this as stale. If this is still an issue, please open a follow up ticket with updated context. Thanks

FWIW, I believe the original issue is probably from the fact that the type did not match correctly due to the strictness of how `object` types work. We probably can provide pointers if we can see the `terragrunt.hcl` and the module being called, so if this ticket is reopened, that additional context will be immensely useful.
