### ISSUE TITLE
Use of `path_relative_to_include` in backend config in remote_state does not work as expected.

### ISSUE THREAD

**Issue by esciara** [gruntwork-io/terragrunt#1469]
## Context

Using `terragrunt version v0.26.7`.
 
According to the documentation to [Keep your backend configuration DRY](https://terragrunt.gruntwork.io/docs/getting-started/quick-start/#keep-your-backend-configuration-dry), when using the following folder layout:
```
stage
├── terragrunt.hcl
├── frontend-app
│   ├── main.tf
│   └── terragrunt.hcl
└── mysql
    ├── main.tf
    └── terragrunt.hcl
```
and the following content:
```terraform
# stage/terragrunt.hcl
remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    bucket = "my-terraform-state"

    key = "${path_relative_to_include()}/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "my-lock-table"
  }
}
```
and
```terraform
# stage/mysql/terragrunt.hcl
include {
  path = find_in_parent_folders()
}
```

## Expected result

When running `terragrunt apply` (or `plan`) in the `stage/mysql` folder, the `key` should be set to `stage/mysql/terraform.tfstate`. (this is also the result given in the `Terraform up and running` book) 

## Actual result

However, the result I obtain is that the `key` is set to `mysql/terraform.tfstate`. (`stage` part missing)

## Steps to reproduce

Here is a reproducible example (using `azurerm`, but I would expect the same result with `aws`):

Folder layout:
```
stage
├── terragrunt.hcl
└── random-app
    ├── main.tf
    └── terragrunt.hcl
```
Files content:
```terraform
# stage/terragrunt.hcl
remote_state {
  backend = "azurerm"

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }

  config = {
    resource_group_name  = "<my_resource_group_name>"
    storage_account_name = "<storage_account_name>"
    container_name       = "<container_name>"
    key = "${path_relative_to_include()}/terraform.tfstate"
  }
}
```
``` terraform
# stage/random-app/terragrunt.hcl
include {
  path = find_in_parent_folders()
}
```
```terraform
# stage/random-app/main.tf
resource "random_password" "a_password" {
  length           = 16
}
```
Run commands:
```shell
$ cd stage/random-app
$ terragrunt plan
```
The backend state is created in the container at `random-app/terraform.tfstate`, not `stage/random-app/terraform.tfstate`.

**Comment by esciara** [comment]
This causes us problems as we are using the same container/bucket for some non prod environments, which share some resources.

Could not find a satisfying way to work around the problem.

**Comment by esciara** [comment]
Additional notes: the doc seems to contradict itself.

In [Reference > Built-in functions](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#path_relative_to_include), it confirms the resulting key should be `stage/random-app/terraform.tfstate`.

in [Features > Keep your remote state configuration DRY](https://terragrunt.gruntwork.io/docs/features/keep-your-remote-state-configuration-dry/#filling-in-remote-state-settings-with-terragrunt), it says it should be `random-app/terraform.tfstate`.

**Comment by yorinasub17** [comment]
The functions works to find the relative path between the included config and where you are including from. I agree the docs are not consistent, but it is actually correct in each of the examples: what's inconsistent is where the root config is located.

For example, in the "Built in functions" example, you will notice that the root config is outside the `stage` or `prod` folder. This is why the relative path between the root config and the child includes the environment. E.g., if the path of the root config is `./terragrunt.hcl`, and the path of the child is `./stage/mysql/terragrunt.hcl`, then the relative path between the two is `stage/mysql`.

Similarly, in the "Keep your remote configuration DRY" example, the root config is in `./terragrunt.hcl` while the child config is in `./mysql/terragrunt.hcl`, producing a relative path of `mysql`.

So given that, in your example, your root config is in `./stage/terragrunt.hcl` with the child in `./stage/random-app/terragrunt.hcl`, producing a relative path of `random-app`, because your root is in the `stage` folder. To resolve this, you will need to put the root config one level above the stage folder so that the relative path includes the environment.

Is there a reason you want your root config file in each environment folder as opposed to having a single one for all environments? Not sure what your needs are, but I might be able to provide pointers on how to do the environment level customizations that drove the need to have a root per env.

**Comment by esciara** [comment]
Thank you for your answer. That clarifies things.

I realised after reading your answer that our setup was a bit peculiar and we changed it to something more conventional. So now things are working fine. Even though, the documentation would probably benefit from consistency on that point.

Thanks!
