### ISSUE TITLE
Support Optional Dependencies

### ISSUE THREAD

**Issue by tomcart90** [gruntwork-io/terragrunt#1483]
I'm currently working on a project where I have a number of different modules which make up our web application stack. We have many of these stacks defined, all of which pull from a set of top-level .hcl terragrunt files (one for each module). Some of these modules are optional for a given stack, in my case for example whether or not to enable AzureAD single sign-on is an optional, and is defined as a separate module. However, I have a module which is dependant on the outputs of the AzureAD module when present. Therefore, having an option within the dependency block to simply enable or disable a given dependency would be really helpful. Right now even if I set `skip_outputs` to `true` terragrunt still expects the module directory (as pointed to by the `config_path` attribute) to exist and contain a `terragrunt.hcl` file.

**Comment by yorinasub17** [comment]
This seems reasonable. Having an `enabled` attribute on the dependency makes sense to me! We're a bit buried with other initiatives at the moment, so would greatly appreciate a PR to add this feature.

**Comment by DoctorPolski** [comment]
I came here looking for a very similar solution. In my case I would like the enabled status to be conditional:

- I also use a super DRY config of single root level HCL files that are used by modules that are deployed in different server environments and different AWS regions.
- This way each module has a state file for any given combination of environment and/or region.
- Occasionally the "primary" region will create a unique value that must be used by the "secondary" regions.
- Clearly the answer to that is for the "primary" to output the value for use as an input to the "secondaries" and to do this by using a `dependency` block.
- The issue is that this causes a dependency cycle that currently cannot be conditionally broken.

My hope is that an attribute such as `enabled` (`TRUE` by default) could evaluate its required boolean via an expression. In this way if the dependency block is to be evaluated and the current region variable is the "primary" then the dependency block will be skipped. Therefore if we are running in "primary" then code execution continues as normal with no dependency requirements but if the region is not "primary" the dependency is actioned and the outputs can be fetched and passed back to the calling region.

I will take a look at the code and attempt a rough PR but does that sound reasonable within the general TerraGrunt ethos @yorinasub17?

**Comment by yorinasub17** [comment]
Adding `enabled` as an attribute on the `dependency` block (via the struct definition) and properly handling the logic in `dependency.go` would do the trick (as the hcl parser will automatically interpret the expressions during the parse step).

**Comment by lorelei-rupp-imprivata** [comment]
I wish this was implemented, this would really solve our use case for blue/green environment flips within terragrunt.

**Comment by ustuehler** [comment]
I am using a dummy configuration to achieve this in my projects - an empty Terraform module with just these files:

```
.terragrunt/mock
├── main.tf
├── outputs.tf
├── terragrunt.hcl
└── variables.tf
```

The `.terragrunt/mock/terragrunt.hcl` looks like this:

```hcl
remote_state {
  backend = "local"
  config = {}

  generate = {
    path = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}
```

The other files are empty and `variables.tf` and `outputs.tf` only exist to make TFLint happy.

Then in my root `terragrunt.hcl` file (or wherever I would need the optional dependency), I set the `config_path` conditionally:

```hcl
dependency "optional" {
  config_path  = local.optional_dependency_config_path != "" ? local.optional_dependency_config_path : "${get_parent_terragrunt_dir()}/.terragrunt/mock"
  skip_outputs = local.optional_dependency_config_path == ""
}
```

I am using Terragrunt 0.31.3, so I'm a bit behind, but I think this would still work in the current version as well.

**Comment by Latyn4ik** [comment]
Hi, what about implementing this flag for dependency block ?

**Comment by mattk-ce** [comment]
Could really use this

**Comment by denis256** [comment]
Released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.50.17
