### ISSUE TITLE
ERRO[0009] Did not find any Terraform files (*.tf)

### ISSUE THREAD

**Issue by s1mark** [gruntwork-io/terragrunt#1667]
### Scenario
* Creating the `.tf` files in the `.terragrunt-cache`  with the `generate` block
* The source is pointing to the `directory` where the `terragrunt.hcl` file exists:
```terraform
terraform {
  source = "..//directory"
}
```
### Result
`ERRO[0009] Did not find any Terraform files (*.tf)`

### Workaround
Create an empty file that ends with `.tf` in the current `directory`

### Request
Would it be possible to overcome `ERRO[0009] Did not find any Terraform files (*.tf)` somehow without the need to create a `dummy.tf` file? terragrunt really just copies the `dummy.tf` to the cache and successfully executes the generated `.tf` files.
Is it possible to ignore `ERRO[0009]` ?

**Comment by brikis98** [comment]
I'm still not entirely clear on what you're trying to do. Could you provide a bit more context?

**Comment by yorinasub17** [comment]
I THINK I follow what you are trying to do, and I believe this would work if you:

- remove the `terraform` block so that it uses the current dir (where the `terragrunt.hcl` file lives) as the tf source.
- add an empty `main.tf` file with a single comment (`# Intentionally empty`).

Closing this as I believe that will achieve what you want. Happy to reopen if there are any follow ups, or if somehow that doesn't work.
