### ISSUE TITLE
terragrunt run-all show seems to break auto-init

### ISSUE THREAD

**Issue by zf-roose** [gruntwork-io/terragrunt#1697]
Hi,

we have a traditional pipeline with plan (saving the planfile), apply (using a planfile), and optional destroy stages, so basically doing:
`terragrunt run-all plan --terragrunt-non-interactive -out "planfile"`
`terragrunt run-all apply --terragrunt-non-interactive "planfile"`
`terragrunt run-all destroy --terragrunt-non-interactive`

To implement some pipeline policies, I convert the binary planfile to a json planfile so that it can be used as input for policy checking, right after generating the planfile:
`terragrunt run-all show -json planfile`

The apply and even destroy stages then start to fail with:
```
│ Error: Could not load plugin
│ Plugin reinitialization required. Please run "terraform init".
```

Observations after some more troubleshooting:
- Prepending`terragrunt run-all init --terragrunt-non-interactive` to each stage (apply, destroy) seems to do as workaround, as suggested in the error message
- Removing just the `terragrunt run-all show -json planfile` alone is enough to avoid the re-init requirement
- When the above "Could not load plugin" error message appears, the lock is also not cleared as if the terraform process crashed, preventing it from removing the lock and I need to clear it manually (our lock is set in a DynamoDB table).

So it looks like the "run-all show" command is somehow invalidating the previous init (even without storing or doing anything with the output).

**Comment by bwhaley** [comment]
@yorinasub17 and I dug in to this a bit today and have some thoughts to share.

For the plugin initialization errors, we believe you may be running in to [this issue](https://github.com/hashicorp/terraform/issues/28802), and in particular [this comment](https://github.com/hashicorp/terraform/issues/28802#issuecomment-848809705). Can you check if the `.terraform` directory (and/or `.terragrunt-cache`) is cached between CI/CD runs?

We also observed that the `terragrunt run-all show -json planfile > planfile.json` (as you noted in our support ticket) will not work as you expect. The reason is that the individual JSON file outputs will all be concatenated together in a single file and will not be valid JSON. For example, if the `run-all show` resulted in three plan files, they wouldn't be captured as individual files. They'd all be in the same file. It would look like this:

```
{"foo": "bar"}
{"foo2": "bar2"}
{"foo3": "bar3"}
```

This isn't valid JSON and couldn't be parsed. This is described [in this issue](https://github.com/gruntwork-io/terragrunt/issues/1525). If you need to do this, you'd need to loop through the modules and run an individual `terragrunt show` for 
each of them.

Finally, I'll note that `run-all plan` has well known caveats. See [the WARNING in the docs](https://terragrunt.gruntwork.io/docs/reference/cli-options/#run-all), and especially [this comment](https://github.com/gruntwork-io/terragrunt/issues/720#issuecomment-497888756).

**Comment by zf-roose** [comment]
The suggestion in [this comment](https://github.com/hashicorp/terraform/issues/28802#issuecomment-848809705) was exactly the solution.  The .terragrunt-cache directory is being cached, but `.terraform.lock.hcl` was not part of it.  After adding this file to the cache, the problem disappeared.

About the invalid json file, in fact we split the output of `run-all show -json planfile` on newline into separate valid json files.  We don't really need to know from which module the planfile is, as long as it is compliant with the rego policy.

Thanks for pointing to the solution and your other related suggestions!

**Comment by bwhaley** [comment]
Great! I'm glad this resolved the problem for you.
