### ISSUE TITLE
expected RFC3339 timestamp  - aws sso

### ISSUE THREAD

**Issue by diepes** [gruntwork-io/terragrunt#1738]
$ terragrunt --version
terragrunt version v0.30.7
$ terraform --version
Terraform v0.15.5
on linux_amd64

$ AWS_PROFILE=sso aws sts get-caller-identity
working so credentials are valid.

Looking at error output is seems to be parsing the current date/time wrong ?
```
$ date -Is
2021-06-30T22:31:06+12:00
```

But in error below  "2021-06-30T**17**:14:29UTC" -> "2006-01-02T**15**:04:05Z**07**:00"  ???
Where does it get the times from ?

```
$ AWS_PROFILE=sso terragrunt init 
ERRO[0000] Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): SSOProviderInvalidToken: the SSO session has expired or is invalid
caused by: expected RFC3339 timestamp: parsing time "2021-06-30T17:14:29UTC" as "2006-01-02T15:04:05Z07:00": cannot parse "UTC" as "Z07:00" 
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

**Comment by yorinasub17** [comment]
This is the same issue as https://github.com/hashicorp/terraform-provider-aws/issues/17372, and the solution is to upgrade the `aws` CLI. See https://github.com/hashicorp/terraform-provider-aws/issues/17372#issuecomment-772205151

Will close this ticket since this is not an issue with terragrunt, but please feel free to reopen if the provided workaround doesn't work!
