### ISSUE TITLE
when using skip, dependent modules fail with "unexpected end of JSON output"

### ISSUE THREAD

**Issue by matttrach** [gruntwork-io/terragrunt#1791]
When developing a module I tend to selectively skip others, I expected the mock_outputs section to be called when a dependent module does not have output (such as when it is skipped).

What I am seeing is that a skipped module causes all dependent modules to fail with "unexpected end of JSON output".

Debug and trace level logs do not really say anything useful, but I noticed when I removed the dependency (specifically the dependency block) in the dependent module I stopped getting the error. 

I tried several tricks to get it to read, such as: 
- removing the output variable from the inputs block in the dependent module
- removing the mock_outputs section of the dependency block
- hard coding the variable, but leaving the dependency block

so far nothing works, if a dependency block exists and that dependency has been skipped, the module fails.
removing the dependency block resolves the error... but I kinda need that output (passing an ip from a server module to an application configure module).

It seems cleaner to work on a module in isolation and reasonable to expect the mock_output to cover the dependency output, but just having the dependency block at all causes Terragrunt to give a JSON parsing error, kinda feels like a bug.

**Comment by matttrach** [comment]
I am not sure how to test it, but the relevant lines in the code seem to be:
https://github.com/gruntwork-io/terragrunt/blob/69aa1c7bbde16d3b6d588c9a519f0ae3bea8724b/config/dependency.go#L697

https://github.com/gruntwork-io/terragrunt/blob/69aa1c7bbde16d3b6d588c9a519f0ae3bea8724b/config/dependency.go#L704

https://github.com/gruntwork-io/terragrunt/blob/69aa1c7bbde16d3b6d588c9a519f0ae3bea8724b/config/dependency.go#L374

I have not put a debugger on it or anything, but it seems like when a dependency is skipped it would default to a json string hard coded to "{}" on line 374, then unmarshalling the json might have problems on 697 or maybe 704 since I am not sure what golang would set the empty value to.

I did find this on stack overflow: https://stackoverflow.com/a/36359711/16135575

**Comment by brikis98** [comment]
I'm trying to understand what you're doing:

1. You have a few Terragrunt modules. Let's some one module, `foo`, has a `dependency` block pointing to another module, `bar`.
1. You set `skip` on `bar`, which has never been applied (and therefore has no outputs).
1. You run `apply` on `foo`, and you're getting an error, because it's not able to read the outputs of `bar`.
1. You are expecting Terragrunt to know to fall back to `mock_ouputs` when `skip` is set?

Is that right?

**Comment by matttrach** [comment]
yes, correct.

**Comment by matttrach** [comment]
or at least not fail with a json parse error, it would be fine if the json output was just empty values

**Comment by nikskiz** [comment]
I ran into the same issue. We tend to use dependency outputs with `Skip =`. This was working with terragrunt version =< `v0.31.5`

An example of where we use a dependency value with Skip:
```hcl
dependency "cluster" {
  config_path                   = "../cluster"
  mock_outputs_merge_with_state = true
  mock_outputs = {
    cluster_name                        = "mocked"
  }
}

skip = dependency.cluster.outputs.cluster_name == "mocked"
```

We are provisioning an EKS cluster and want to skip the current "config" module being called on the first ever `plan`. The config module expects a cluster to be present and accessible so that it can populate the provider credentials for kubernetes and helm.
