### ISSUE TITLE
Add `skip_outputs` to `ModuleDependencies`

### ISSUE THREAD

**Issue by dmattia** [gruntwork-io/terragrunt#1801]
The `ModuleDependencies` struct currently only contains `paths`.

https://github.com/gruntwork-io/terragrunt/blob/d3af798f9b47b90428dd31b62b8e1236904496be/config/config.go#L233-L237

For my work in https://github.com/transcend-io/terragrunt-atlantis-config, I would like to not count `dependency` blocks that have `skip_outputs` set to true.

Would it be possible to add that field to the struct?

**Comment by yorinasub17** [comment]
This struct represents the deprecated `dependencies` block which doesn't have `skip_outputs`. Assuming you are getting this from the top level `TerragruntConfig` struct, you want to use `TerragruntDependencies` instead of `Dependencies`.

Closing as I don't think there is anything to change in terragrunt, but please reopen if you think otherwise!
