### ISSUE TITLE
CLI flag `-backend-config` broken

### ISSUE THREAD

**Issue by justinTM** [gruntwork-io/terragrunt#1851]
Usually, when running locally (instead of in hosted CI/CD repo), the following is used to plan:
```shell
export TOKEN=<YOUR-ACCESS-TOKEN>
terragrunt plan \
    -backend-config="address=https://..." \
    -backend-config="lock_address=https://..." \
    -backend-config="unlock_address=https://..." \
    -backend-config="username=me" \
    -backend-config="password=$TOKEN" \
    -backend-config="lock_method=POST" \
    -backend-config="unlock_method=DELETE" \
    -backend-config="retry_wait_min=5"
```

however, recently, it appears to be broken:
```console
Initializing the backend...
address
  The address of the REST endpoint

  Enter a value: 
```

**Comment by yorinasub17** [comment]
`-backend-config` is an arg for `terraform init`, not `terraform plan`. There are two issues here:

- Terragrunt does not pass through the CLI args to the `init` command in auto-init. This is by design, as `init` won't be able to parse the command flags you intend to pass through to the other commands.

- Even if Terragrunt did pass through, Terraform won't be able to handle the `-backend-config` flag for the `plan` command. You will get the following error:
```
╷
│ Error: Failed to parse command-line flags
│
│ flag provided but not defined: -backend-config
╵

For more help on using this command, run:
  terraform plan -help
```

It should work if you did `terragrunt init -backend-config...` and then `terragrunt plan`.
