### ISSUE TITLE
iam_role is broken in v0.34.0

### ISSUE THREAD

**Issue by dudicoco** [gruntwork-io/terragrunt#1853]
Hi,

We're using the following configuration in order to make terragrunt work in a multi-account config:

```hcl
iam_role = "arn:aws:iam::${local.common_vars.account_id}:role/terragrunt"

remote_state {
  backend = "s3"

  config = {
    encrypt        = true
    bucket         = "${local.common_vars.account_alias}-terraform"
    region         = "us-east-1"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    acl            = "bucket-owner-full-control"
    dynamodb_table = "terraform"

    dynamodb_table_tags = {
      Provisioner = "terraform"
    }
  }
}

locals {
  common_vars = merge(
    yamldecode(
      file(find_in_parent_folders("account.yaml", "${get_parent_terragrunt_dir()}/empty.yaml"))
    ),
    yamldecode(
      file(find_in_parent_folders("region.yaml", "${get_parent_terragrunt_dir()}/empty.yaml"))
    ),
    yamldecode(
      file(find_in_parent_folders("environment.yaml", "${get_parent_terragrunt_dir()}/empty.yaml"))
    ),
  )
}
```

After upgrading to v0.34.0, i'm getting the following error when running plan on a component in a different account:
```
│ Error: Failed to load state: AccessDenied: Access Denied
│ 	status code: 403, request id: xxxxxxxxxx, host id: xxxxxxxxxx
```

**Comment by denis256** [comment]
Hello, recently was updated how `iam_role` to avoid cases when it is replaced from the environment variables and not evaluated from variables.

I prepared a small example in https://github.com/denis256/terragrunt-test-1853 which load `account_id` / `account_alias` from yaml files, I hope it will help:

```
$ aws sts get-caller-identity
...
"Arn": "arn:aws:sts::666:assumed-role/denis-account"
...

$ tree
.
├── account.yaml
├── app
│   ├── app.tf
│   └── terragrunt.hcl
├── empty.yaml
└── region.yaml
1 directory, 5 files
$ cd app
$ terragrunt_linux_amd64_0_34_1 plan  --terragrunt-log-level debug --terragrunt-debug
...
DEBU[0000] Assuming IAM role arn:aws:iam::test1:role/terragrunt with a session duration of 3600 seconds. 
...
```
So in this example, Terragrunt tries to assume IAM role `test1` defined in `account.yaml`.

https://github.com/gruntwork-io/terragrunt/issues/667

**Comment by yorinasub17** [comment]
@denis256 I see the bug. The issue is that https://github.com/gruntwork-io/terragrunt/blob/master/config/dependency.go#L441 is inheriting the `IamRole` from the original config calling the `dependency`. This made sense prior to the feature we implemented, because `IamRole` was only set from the command line, but now that the config is updating it, this logic needs to be updated.

I wanted to avoid this, but I think to resolve this, we will need to track if the `IamRole` came from the CLI or not. That is, in addition to `IamRole`, we should have an `OriginalIamRole` field on the options struct that is only set from the CLI, and in the `cloneTerragruntOptionsForDependencyOutput` function, we clear out `IamRole` if it is not equal to `OriginalIamRole` so that the subsequent calls will set it accordingly from the config.
