### ISSUE TITLE
failed to get console mode: The handle is invalid

### ISSUE THREAD

**Issue by imti283** [gruntwork-io/terragrunt#1854]
Running terragrunt run-all plan/apply/show works fine in pwsh command line, But running same command in PowerShell ISE or in pipeline using PowerShell fails with error -
      _**terragrunt : time=2021-10-11T12:36:52+05:30 level=error msg=failed to get console mode: The handle is invalid**_.

Here is the **working** output from **PowerShell command** line - 

```
PS C:\tf\tg> terragrunt run-all plan --terragrunt-include-dir "/us-west-2/pro/maintenance" -input=false -out plan.out
time=2021-10-10T23:16:26+05:30 level=info msg=Stack at C:/tf/tg:
  => Module C:/tf/tg/us-west-2/pro/app1 (excluded: true, dependencies: [C:/tf/tg/us-west-2/pro/maintenance])
  => Module C:/tf/tg/us-west-2/pro/maintenance (excluded: false, dependencies: [])
  => Module C:/tf/tg/us-west-2/pro/app2 (excluded: true, dependencies: [C:/tf/tg/us-west-2/pro/maintenance])`
```

Here is the **NON working** output from **PowerShell ISE command** line - 

```
PS C:\tf\tg> terragrunt run-all show --terragrunt-non-interactive -no-color -input=flase --terragrunt-include-dir "/us-west-2/pro/maintenance" plan.out 
terragrunt : time=2021-10-11T12:36:52+05:30 level=error msg=failed to get console mode: The handle is invalid.
At line:1 char:1
+ terragrunt run-all show --terragrunt-non-interactive -no-color -input 
    + CategoryInfo          : NotSpecified: (time=2021-10-11...dle is invalid.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
time=2021-10-11T12:36:52+05:30 level=error msg=failed to get console mode: The handle is invalid.
time=2021-10-11T12:36:52+05:30 level=info msg=Stack at C:/tf/tg/:
  => Module C:/tf/tg/us-west-2/pro/app1 (excluded: true, dependencies: 
[C:/tf/tg/us-west-2/pro/maintenance])
  => Module C:/tf/tg/us-west-2/pro/maintenance (excluded: false, dependencies: [])
  => Module C:/tf/tg/us-west-2/pro/app2 (excluded: true, dependencies: 
[C:/tf/tg/us-west-2/pro/maintenance])
```

I can live with my local system using pwsh cmd or normal cmd, But unfortunately my Azure devops self hosted agent when runs these command as PowerShell task, it fails with same error.

**Comment by imti283** [comment]
> Was this an error in your command line command? I see `-input=flase` in your snippet.

It is in PowerShell ISE 

> After investigation, I believe this is a non-fatal error. What's failing is this routine https://github.com/gruntwork-io/terragrunt/blob/master/shell/ptty_windows.go#L16, which doesn't bubble up the errors from the underlying functions. What's broken when this fails is that the escape sequences don't get processed correctly on print, so it doesn't print in color correctly. However, the underlying terragrunt processes should work as normal.
> 
> Can you double check if the command exits with a 0-exit code despite the errors?
> 
> For reference, this is the syscall that is failing: https://docs.microsoft.com/en-us/windows/console/getconsolemode

Exit code ($LASTEXITCODE) is 0 and the output is as expected, so non-fatal. Normal cmd still works fine, but the same happens in   my azure devops pipeline powershell task. There also it is non-fatal, but I think i need to catch this to avoid actual error from being missed. But if it works as in other console, that would be great.
![tg_error](https://user-images.githubusercontent.com/32821195/136915886-ee1f8cb5-bc7c-41b4-a992-58cf027b0cb7.png)

**Comment by robcortez** [comment]
I see that this issue is still open and awaiting triage. Just wanted to add that I am getting the same, non-fatal errors both on my local machine (Powershell  5.1) and on my Azure build agents. 

Colors are displaying correctly but this error appears three times for each terragrunt command that gets run: 

```
*** build.ps1 - invoking terragrunt plan
time=2022-10-06T15:27:11Z level=error msg=failed to get console mode: The handle is invalid.

time=2022-10-06T15:27:11Z level=error msg=failed to get console mode: The handle is invalid.

time=2022-10-06T15:27:11Z level=error msg=failed to get console mode: The handle is invalid.
```

Although it's not critical and does not affect the functionality of terragrunt/terraform, it does pollute the logs and make it more difficult to spot actual errors.

**Comment by Xiphoseer** [comment]
I came across this while trying to run `terragrunt hclfmt` in [pre-commit], which has the same issue. `pre-commit` doesn't pass on the standard I/O handles, because it hides the output of a successful hook, so it needs to capture it.

The main issue is that any such redirection produces an I/O handle of  `FILE_TYPE_PIPE` (3), whereas "normal" console handles are always of `FILE_TYPE_CHAR` (2) (see [GetFileType]). There is the theoretical possibility of an I/O stream which is not a console for handles to devices such as printers. All three streams are pipes if you use something like [Python3 `subprocess`][py3-subprocess], but it's possible to only redirect one of the streams e.g. with PowerShell pipes. It's possible to get a `FILE_TYPE_DISK` with a `> filename` within `cmd.exe`.

In any case, it's always invalid to call [GetConsoleMode] on a pipe, so terragrunt should not attempt that or at least not produce an error.

It seems like the best effort terragrunt could make is to add `-no-color` to the terraform arguments if stdout or stderr failed to set the mode. But, at least on my system (Win11) I need to redirect the output to a file in order to even get to see stray VT sequences, even in old-school conhost.

So my recommendation would be to:
- mirror terraform, producing VT sequences by default.
- continue to passthrough `-no-color`
- change the log level of "failed to get console mode" to `debug`
- maybe special-case pipes and add a less confusing debug note

There is one other option, which would be to call `CreateFileA` on `CONOUT$` as per [the GetStdHandle docs](https://learn.microsoft.com/en-us/windows/console/getstdhandle#remarks), and to use that to add VT processing to the console mode. On the other hand, that seems to be about the only way to get a console *without* VT handling on modern Windows too, and doing that bypasses any nesting of programs in the same console window, which seems not justified to me.

[go:GetFileType]: https://pkg.go.dev/syscall?GOOS=windows#GetFileType
[pre-commit]: https://pre-commit.com/
[py3-subprocess]: https://docs.python.org/3/library/subprocess.html
[GetFileType]: https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfiletype
[GetConsoleMode]: https://learn.microsoft.com/en-us/windows/console/getconsolemode

**Comment by williamoconnorme** [comment]
This issue surfaced for me when using the command `terragrunt output`. The command has parameters of `-raw` and `-json` which makes working with outputs convenient in shell scripts. However the output values are polluted due to this error message

**Comment by albers** [comment]
This is not ony a Powershell problem.
I also run into this issue when using terragrunt in a Cygwin shell:

```shell
# calling terragrunt in a command substitution gives error message
$ keyvault=$(terragrunt output -raw key_vault_name)
time=2023-09-13T12:49:27+02:00 level=error msg=failed to get console mode: Das Handle ist ungültig.

# the command runs successfully, though.
$ echo $keyvault
somekeyvaultname

# calling terrafrom directly gives no error
$ terragrunt output -raw key_vault_name
somekeyvaultname
```

**Comment by denis256** [comment]
Released fix in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.50.16
