### ISSUE TITLE
Referencing aws data source in terragrunt

### ISSUE THREAD

**Issue by hunkeelin** [gruntwork-io/terragrunt#1945]
How can I reference aws resource for terragrunt? 

```
terraform {
  source = // some source
}

/*
provider "aws" {
  region = "us-east-1"
}

data "aws_secretsmanager_secret" "foo" {
  name = "foo"
}
data "aws_secretsmanager_secret_version" "current" {
  secret_id = data.aws_secretsmanager_secret.foo.id
}
*/
inputs = {
   username  = jsondecode(data.aws_secretsmanager_secret_version.current.secret_string)["username"] // using it as input
   password  = jsondecode(data.aws_secretsmanager_secret_version.current.secret_string)["password"]
}
```

How to properly do what I am trying to do above?

**Comment by yorinasub17** [comment]
This is not currently supported in terragrunt, and we don't quite have plans to support this due to complexities of implementing data source pipeline (see https://github.com/gruntwork-io/terragrunt/issues/1150#issuecomment-626046714).

Your options for work around are:

- Create a module that runs the data source and outputs the results, and use `dependency` blocks to feed it in to the target module.
- Use `run_cmd` and `jsondecode` with the aws CLI instead of terraform data sources to look up the relevant data from within terragrunt.

**Comment by yorinasub17** [comment]
If we do end up implementing a data source system, we will provide updates on https://github.com/gruntwork-io/terragrunt/issues/1150, so please follow that for updates on this feature. Thanks!

**Comment by jonjpbm** [comment]
It would be nice to provide some bare bones workaround. Data sources seems like something that could be used all over the place in some terraform implementations and to have to account for all them by one of three options is bad at best. Especially since it is a provided out of the box by the thing that you are wrapping. 

here are the workarounds that I found in another issue: https://github.com/gruntwork-io/terragrunt/issues/254
Again, bad at best.

**Comment by manku211** [comment]
same pls check  issue #254 as it looks not related to this
