### ISSUE TITLE
No double-slash (//) found in source URL

### ISSUE THREAD

**Issue by leiarenee** [gruntwork-io/terragrunt#1963]
I'm fed up of this warning. I wish there was a way of disabling it. I'm using local modules that are in one single repository.

**Comment by canidam** [comment]
This seems to be an easy fix, and good for new comers. Is PR welcome for this issue?

**Comment by timblaktu** [comment]
@leiarenee would you provide an example terragrunt project tree that uses local modules and exhibits this warning, including the relevant `terragrunt.hcl` and `*.tf` contents? I'm also using local modules and seeing this WARNing, and although I find it similarly annoying, I'm too new to terragrunt to _think_ that it's not telling me something I'm actually doing wrong.

Here's a simplified project of mine that produces this WARNing on `terragrunt run-all validate`. It also produces some other errors I believe to be related to module source path declaration (`Unsupported Attribute` in dependency, `No such file or directory`), and I want to make sure I fully understand module source paths, relative paths (to dependencies' `config_path`, hooks' `execute` paths, ), and best practice here.

```
.
├── backend.tf                    # Generated by root terragrunt.hcl
├── globals.hcl
├── modules
│   ├── account
│   │   ├── data
│   │   │   ├── main.tf
│   │   │   └── terragrunt.hcl
│   │   └── terragrunt.hcl        # Empty
│   ├── region
│   │   ├── data
│   │   │   ├── main.tf
│   │   │   └── terragrunt.hcl
│   │   └── terragrunt.hcl        # Empty
│   ├── terragrunt.hcl            # Empty
│   └── vpc
│       └── terragrunt.hcl
├── provider.tf
├── script
│   ├── colorfuncs.sh
│   ├── functions.sh
│   └── terragrunt-workspace-hook.sh
├── terraform.tfstate.d
│   └── proto67
├── terragrunt.hcl
└── versions_override.tf
```

**Comment by leiarenee** [comment]
I've solved this problem with a workaround like many others I guess by using '//' somewhere in local path.

Eg.  https://github.com/leiarenee/sf-infra/blob/main/infra/live/k8s-deploy/namespace/terragrunt.hcl
```terraform
source = "${get_parent_terragrunt_dir()}//library/terraform/modules/deploy-yaml"
```

Or 
```terraform
source = ".//terraform"
```

Where TF code is written directly under TG folder structure as in 
https://github.com/leiarenee/sf-infra/blob/main/infra/live/job-resources/terragrunt.hcl

So maybe we should close it and accept it as it is :-)

**Comment by timblaktu** [comment]
@leiarenee thanks for your response. I've updated my previous post with much more detail about my use case and the errors I'm trying to resolve. 

@leiarenee @canidam Would you take a quick look at my above post and see if any config problems jump out at you? 

If this turns out to be unrelated to double-slashes in local module source paths, I can create a new issue, but as I'm so new to terragrunt, I'm still assuming this is cockpit error on my part. Thanks.

Also, @canidam I've traced [the line in `splitSourceUrl` that logs this warning over on my fork](https://github.com/timblaktu/terragrunt/blob/master/cli/tfsource/types.go#L241) back to [where it's called in `NewTerraformSource`](https://github.com/timblaktu/terragrunt/blob/master/cli/tfsource/types.go#L145), which is clearly happening just before [the `IsLocalSource` check, when the func becomes aware of whether the source is local or remote](https://github.com/timblaktu/terragrunt/blob/master/cli/tfsource/types.go#L150). I don't have the full picture here, but it looks like _iff we really wanted to silence this warning for local sources_ we may be able to either change order of operations here, or simply add a conditional branch around the logger call inside `SplitSourceUrl()`. But, **after reading and experimenting so much with local module sources and confirming that the double-slash is just as important for them as it is for remote URLs, I think we should not make any change here.**

**Comment by timblaktu** [comment]
@leiarenee I looked over your repo, and it appears we're doing mostly similar things WRT the double-slash and using relative paths. One question I had was why do you use relative paths like `../` sometimes for `source` and other times you use the absolute: `"${get_parent_terragrunt_dir()}//some/module"`?

Also I don't understand how/if you're actually using mocked outputs there. I see your mock.hcl files, but don't see how they're being used. Do/did you actually run `terragrunt run-all validate` in your workflow, before deploying resources with `terragrunt run-all apply`? 

On the one hand the problem I'm having is a well-known limitation of terragrunt: you can't expect to validate before apply without setting up adequate mocks. But I believe I have set these up and am still encountering the "Unsupported attribute" issue.

**Comment by denis256** [comment]
Improved checking of module path in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.50.13
