### ISSUE TITLE
include_in_copy for local modules does not apply recursively (sometimes).

### ISSUE THREAD

**Issue by DevAndrewGeorge** [gruntwork-io/terragrunt#2067]
Take a module located on the local disk with the following file structure:
```
../_module/
├── .f0
├── f1
│   ├── .f1
│   └── f2
│       ├── .f0
│       └── .f2
└── main.tf
```

And take a related `terragrunt.hcl` file:
```
terraform {
    source = "${get_terragrunt_dir()}/../_module"
    include_in_copy = [".f0", ".f1", ".f2"]
}
```

After running `terragrunt init`, only the following files are found:
```
$ find .terragrunt-cache/ -name ".f[0-9]"
.terragrunt-cache//r0qJlJcTEUJUSPWytB0cIdI9fGE/BUp2nRZllUU-nmK5nE9sbD6WM1Q/.f0
.terragrunt-cache//r0qJlJcTEUJUSPWytB0cIdI9fGE/BUp2nRZllUU-nmK5nE9sbD6WM1Q/f1/f2/.f0
```

Notably, the files `f1/.f1` and `f1/f2/.f2` are missing despite being included in the `include_in_copy` list.  

Diving a bit deeper into the issue, each of the following patterns successfully select `.f0` when specified individually:
```
include_in_copy = [".f0", "*.f0", ".f0*", ".f*", "**/.f0", "**/*.f0", "**/.f0*", "**/.f*"]
```

However, none of the following patterns select `f1/.f1`:
```
include_in_copy = [".f1", "*.f1", ".f1*", ".f*", "f1/.f1", "f1/*.f1", "f1/.f1*", "f1/.f*", "**/.f1", "**/*.f1", "**/.f1*", "**/.f*"]
```

And strangest of all, take note that because `.f0` appears in the module's root directory, `f1/f2/.f0` is also copied as a result, but if you were to remove `.f0` from the root directory, `f1/f2/.f0` is not longer copied.

Thoughts? Am I missing something?

This seems like a bug. Terragrunt recursively copies if and only if the desired file exists in the module's root directory.

For the record, I'm on Terragrunt 0.36.6.

**Comment by denis256** [comment]
Hi,
looks like a bug will look in more details

**Comment by btsuhako** [comment]
also seeing similar behavior with `0.36.6`

We have a Helm chart within our Terragrunt repository, and we need to copy over a hidden file with the following config:

```hcl
terraform {
  source = "${get_parent_terragrunt_dir()}//modules/my_helm_chart"
}

  include_in_copy = [
    ".helmignore",
    "**/.helmignore",
  ]
}
```

I `find` and inspect the contents of the `.terragrunt-cache` dir, and cannot find that file, even though it definitely exists in the `modules/my_helm_chart` dir. if i change to `include_in_copy = [ ".gitignore"]`, then I do find that hidden file copied in the cache dir

**Comment by slawekzachcial** [comment]
I'm having the same issue with `.helmignore`. I have Terraform module located in my repo (`modules/app`) that contains a chart folder (`modules/app/chart`) that contains `.helmignore` file. In my `config/app/dev/terragrunt.hcl` I have the following:
```
terraform {
  source = "../../..//modules/app"
  include_in_copy = [
    "./modules/app/chart/.helmignore"
  ]
}
```

I think the issue is in [CopyFolderContentsWithFilter](https://github.com/gruntwork-io/terragrunt/blob/f9f76373bb387b78b8198a90cb42cd4b73786efd/util/file.go#L210) function. This function is [first called](https://github.com/gruntwork-io/terragrunt/blob/f9f76373bb387b78b8198a90cb42cd4b73786efd/util/file.go#L199) passing in a [closure function](https://github.com/gruntwork-io/terragrunt/blob/f9f76373bb387b78b8198a90cb42cd4b73786efd/util/file.go#L200-L203) to filter files to be included in the copy. The closure function uses [includeExpandedGlobs](https://github.com/gruntwork-io/terragrunt/blob/f9f76373bb387b78b8198a90cb42cd4b73786efd/util/file.go#L195) variable, defined outside of its scope, that contains a list of paths expanded from `include_in_copy` (e.g. `[modules/app/chart/.helmignore]`).

For me the problem is that the function `CopyFolderContentsWithFilter` would walk through the directory tree calling itself [recursively](https://github.com/gruntwork-io/terragrunt/blob/f9f76373bb387b78b8198a90cb42cd4b73786efd/util/file.go#L253) on source sub-paths as it walks the tree, but passing always the same filter function with the original list of expanded paths.

I believe the match would only happen for `include_in_copy` expanded paths that have no directories (i.e. they are at root of the original source). That's probably why it works for `.gitignore` but no other files deeper in the directory structure like `modules/app/chart/.helmignore`.

**Comment by slawekzachcial** [comment]
I create [this PR](https://github.com/gruntwork-io/terragrunt/pull/2112) to get the discussion and hopefully a fix going.

**Comment by denis256** [comment]
Fix included in release https://github.com/gruntwork-io/terragrunt/releases/tag/v0.37.4
