### ISSUE TITLE
AWS Profiles

### ISSUE THREAD

**Issue by pixie79** [gruntwork-io/terragrunt#21]
Hi,

How does terragrunt interact with different AWS account credentials? Is there an option to set the profile in the config or will it respect the AWS_DEFAULT_PROFILE variable to get the correct API keys for use.

Thanks

Mark

**Comment by josh-padnick** [comment]
Hi @pixie79, thanks for the question!

Since terragrunt is written in Go and uses the [AWS SDK for Go](https://docs.aws.amazon.com/sdk-for-go/latest/v1/developerguide/welcome.title.html), the AWS authentication is handled completely by the AWS SDK. 

You can read about the [specific authentication hierarchy used by the AWS SDK](https://docs.aws.amazon.com/sdk-for-go/latest/v1/developerguide/configuring-sdk.title.html), which clarifies that terragrunt will first look for the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`. If those are undefined, it will use the shared credentials file, and I'm guessing it will also respect the `AWS_DEFAULT_PROFILE` env var, though this would ultimately be up to the AWS SDK.

If this answered your question, feel free to close this issue. Otherwise, I'll leave it open for a bit in case you have any follow-up questions.

**Comment by mmorianos** [comment]
I notice you don't support the use of temporary credentials which require a 3rd environment variable, AWS_SESSION_TOKEN.  We don't use IAM:users or issue long term access keys, instead we built a service that pulls temporary credentials via STS to provide access.  It looks like the SDK supports STS but not sure the level of effort to include that with terragrunt.

**Comment by brikis98** [comment]
@mmorianos We are using the [default credentials providers](https://github.com/gruntwork-io/terragrunt/blob/master/dynamodb/dynamo_lock.go#L96) from the AWS Go SDK. Following that code SDK code, it uses the [CredChain function](https://github.com/aws/aws-sdk-go/blob/master/aws/defaults/defaults.go#L36), which includes an [EnvProvider](https://github.com/aws/aws-sdk-go/blob/master/aws/defaults/defaults.go#L91), which, at least in theory, includes the [AWS_SESSION_TOKEN environment variable](https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/env_provider.go#L69).

Did you try it setting the three environment variables (`AWS_ACCESS_KEY_ID `, `AWS_SECRET_ACCESS_KEY `, and `AWS_SESSION_TOKEN`) and find that it didn't work? If so, what error did you get?

**Comment by ryangardner** [comment]
What's interesting is that it does seem to use the SESSION_TOKEN_ID to create the table for me, but then fails to write an entry in the statefile with it. 

I deleted the lock table and tried from scratch with those environment variables exported (`AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_SESSION_TOKEN`): 

```
[terragrunt] 2016/09/13 10:32:07 Remote state is already configured for backend s3
[terragrunt] 2016/09/13 10:32:07 Attempting to acquire lock for state file sherpa-services-lock in DynamoDB
[terragrunt] 2016/09/13 10:32:07 Lock table terragrunt_locks does not exist in DynamoDB. Will need to create it just this first time.
[terragrunt] 2016/09/13 10:32:07 Creating table terragrunt_locks in DynamoDB
[terragrunt] 2016/09/13 10:32:07 Table terragrunt_locks is not yet in active state. Will check again after 10s.
[terragrunt] 2016/09/13 10:32:17 Table terragrunt_locks is not yet in active state. Will check again after 10s.
[terragrunt] 2016/09/13 10:32:28 Success! Table terragrunt_locks is now in active state.
[terragrunt] 2016/09/13 10:32:28 Attempting to create lock item for state file sherpa-services-lock in DynamoDB table terragrunt_locks
[terragrunt] 2016/09/13 10:32:28 InvalidClientTokenId: The security token included in the request is invalid
	status code: 403, request id: e56e58a3-79be-11e6-a898-cf1ede838a3b
```

So, part of it works (creating the table) but part of it doesn't work (creating the lock item in the table)

**Comment by brikis98** [comment]
@ryangardner Hm, if some of the requests work, I think that means the auth is working. Perhaps "The security token included in the request is invalid" is just a poorly worded error message that actually means you lack the IAM permissions to write to that table?

**Comment by brikis98** [comment]
@ryangardner Ah, after a quick google search, I have an alternative theory: when creating a lock, the [terragrunt code calls the IAM GetUser API](https://github.com/gruntwork-io/terragrunt/blob/master/dynamodb/dynamo_lock_item.go#L114). As I found from [this comment](https://github.com/hashicorp/terraform/issues/3243#issuecomment-206905233) in Terraform's issue tracker (which is relevant, since Terraform also uses the AWS Go SDK), if you are using the AWS APIs with dynamic credentials generated by `GetSessionToken`, those credentials cannot be used to make IAM calls unless you are using MFA. 

Could you test this theory out? Use the AWS CLI to make some random API call (e.g. list the contents of an S3 bucket) and make sure it works with those env vars. Then, try this:

```
aws iam get-user
```

I'm guessing you'll get the same "security token included in the request is invalid" error.

**Comment by mmorianos** [comment]
yep, that's the problem.

aws iam get-user

An error occurred (InvalidClientTokenId) when calling the GetUser operation: The security token included in the request is invalid

**Comment by brikis98** [comment]
Could you try enabling MFA and seeing if that fixes the issue?

**Comment by brikis98** [comment]
@mmorianos Ah, nice find! I think `sts:GetCallerIdentity` will work perfectly here. 

Anyone interested in submitting a PR?

**Comment by ryangardner** [comment]
I submitted a PR for this - as a side bonus of switching to `sts:getCallerIdentity` you don't need to have the `iam:getUser` permission anymore

**Comment by brikis98** [comment]
A huge thanks to @ryangardner for submitting a fix. I've merged it in and just created a new release:

https://github.com/gruntwork-io/terragrunt/releases/tag/v0.0.11

The CircleCI build is running now and in 5-10 minutes, the new binaries should be available at the URL above. Please give them a shot and let me know if things are working for you!

**Comment by zerolaser** [comment]
so, The terragrunt will be retrieving aws credentials for remote state and dynamodb table. when `terragrunt plan/apply` is performed it in-turn runs the `terraform plan/apply` which again  retrieves the aws credentials and applies the infrastructure.  correct me if i am wrong.

**Comment by brikis98** [comment]
@zerolaser Yes, that sounds right. Is that a problem?

**Comment by zerolaser** [comment]
@brikis98 I do have multiple aws credentials set in ~/.aws/credentials. so when I pass `profile = prod`  to the provider, The terraform is using prod credentials while terragrunt is using default credentials.Is there any work around for this ?

**Comment by brikis98** [comment]
@zerolaser Have you tried the `AWS_DEFAULT_PROFILE` environment variable?

**Comment by brikis98** [comment]
Or maybe it's just `AWS_PROFILE`? Not sure.

**Comment by zerolaser** [comment]
@brikis98 setting AWS_PROFILE worked. thanks.

**Comment by brikis98** [comment]
OK, I'm going to mark this bug as closed. If anyone is still having issues, let us know, and we can re-open.

**Comment by karl-barbour** [comment]
@brikis98 looks like I'm still having this issue.

```
[karl.barbour@xxx tf_poc]$ terragrunt apply
[terragrunt] 2016/12/21 15:04:13 Reading Terragrunt config file at .terragrunt
[terragrunt] 2016/12/21 15:04:13 Initializing remote state for the s3 backend
[terragrunt] 2016/12/21 15:04:13 Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid providers in chain. Deprecated. 
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
[karl.barbour@xxx tf_poc]$ echo $AWS_DEFAULT_PROFILE 
poc-account
[karl.barbour@xxx tf_poc]$ echo $AWS_PROFILE 
poc-account
```

As you can see, the env vars are working. 

Versions:
terragrunt `0.7.1`
aws-cli `1.10.47`
Darwin `15.5.0`

Any ideas?
