### ISSUE TITLE
Create certificate in different region

### ISSUE THREAD

**Issue by benno85** [gruntwork-io/terragrunt#2159]
Hi,
i want to create a cloudfront distribution in "eu-central-1". The distribution itself is creating properly. 

My proplem now is the distribution needs a "viewer-certificate" and this certificate has to be created in "us-east-1".
How can i change the region for creating the "aws_acm_certificate" Because right now the region is set globally in the terragrunt.hcl file for all resources in this module. But i need a different region just for this specific resource.

When i am adding a "region" attribute to my "aws_acm_certificate" resource i receive the error " An argument named "region" is not expected here."

Hopefully my explanations are somehow clear and you can help me configure it out.

Thanks!

**Comment by yorinasub17** [comment]
This is more of a Terraform question, which is best directed to [Hashicorp discussion forum](https://discuss.hashicorp.com/c/terraform-core/27), but in any case, to do what you need, you need to create another aws provider block and set an `alias` on it so that the resources can independently reference the different providers.

You can refer to [this blog post entry](https://blog.gruntwork.io/terraform-up-running-3rd-edition-early-release-is-now-available-4efd0eb2ce0a#f5b5) for more info.

**Comment by yorinasub17** [comment]
Closing as unrelated to terragrunt.
