### ISSUE TITLE
Approach to multi accounts?

### ISSUE THREAD

**Issue by larsrnielsen** [gruntwork-io/terragrunt#217]
Hi,

   I have a live folder structure with environments (dev, test, prod) as sub directories. Each environment will have their own VPC created by different AWS accounts. At least for me it is a bit difficult to figure out, if I should use profile when creating the bucket and extra variables with a `-var profile=dev-user/test-user/prod-user` for each environment, or something else? Of course, I also have the messy shared-services with peering to dev, test and production to support, but is it best practice to use one profile for all the locks to be able to share state (e.g., CIDR blocks)? Or do you just hardcode the few cross-VPC dependencies? I would like that all developers can update the dev environment, while production is only known to a few people, so I guess re-using the same profile for all lock files are not the best approach. Any suggestions?

Lars

**Comment by dpetzel** [comment]
I have tackled this via the use of profiles. I'm in a similar situation to you with multiple accounts, and one account devs have lots of access to to, but not others. By using profiles you can safely prevent anyone from accidentally messing with QA or production. 

I personally avoid the usage of the profile variable, and let terraform do its thing and read the profile from environment variable (this way I set it once for all the AWS tools I use). IE by using the env var, you can instruct devs to export it, then they are instantly setup for both terraform and AWS CLI tools + plus pretty much any other SDK that leverages it.

**Comment by larsrnielsen** [comment]
How do you deal with an `apply-all` in the root folder (live)? I mean, when terragrunt works in the dev subfolder, it should be instructed to use the dev-user and instruct terraform to the same, and then test-user when working in the test sub-folder, and so on... How do you set the AWS_ environment variables differently for each folder?

**Comment by dpetzel** [comment]
Since they are an *environment* variable, I don't set them per folder. If you haven't seen it already you may want to peek at https://github.com/gruntwork-io/terragrunt/issues/169. we've been having some similar discussions around directory structure there. 

In my case a user sets up their credentials file (https://aws.amazon.com/blogs/security/a-new-and-standardized-way-to-manage-credentials-in-the-aws-sdks/). Generally speaking folks just populate their default profile. For those users who actually do have access to more than one account, they setup multiple profiles and exporting `AWS_PROFILE` for the account they wish to interact with. 

Using this approach they can only ever be configured for a single environment at a time. 

Additionally in my case I personally don't have my project setup to support apply-all from root. I have my structure something like this.
```

├── us-east-1
│   ├── dev
│   │   └── terraform.tfvars
│   ├── prod
│   │   └── terraform.tfvars
│   └── qa
│       └── terraform.tfvars
└── us-west-2
    ├── dev
    │   └── terraform.tfvars
    ├── prod
    │   └── terraform.tfvars
    └── qa
        └── terraform.tfvars

```
I've done it this way to explicitly avoid an apply-all across my entire infrastructure, as I want to make sure my largest blast radius is a specific environment in a given region. You're requirements of course might be different, but essentially it boils down to how you organize the folders.

**Comment by larsrnielsen** [comment]
thanks - I changed my folder structure as you suggested. Your reference to #169 really helped me.
