### ISSUE TITLE
invoke terraform directly instead of terragrunt

### ISSUE THREAD

**Issue by gregwebs** [gruntwork-io/terragrunt#22]
I would like to use terraform directly if possible. With this layer on top it is possible for someone to just invoke `terraform` directly instead of using `terragrunt`.

Is it possible to make terragrunt a terraform plugin or possibly a data source such that I can put 1 line into a terraform file that will ensure that terragrunt is installed for `terraform plan` to be able to be run successfully?

**Comment by josh-padnick** [comment]
Hi @gregwebs!

In our [blog post introducing terragrunt](https://docs.aws.amazon.com/sdk-for-go/latest/v1/developerguide/welcome.title.html), under the section **Why not just submit Pull Requests to Terraform?**, we give the specific reasons why we wrote a separate tool versus submitting a few Pull Requests to update Terraform directly. But we also clarify that while our short-term goal with Terragrunt is to get community feedback and empower our own clients, our ultimate goal is to see this functionality implemented directly in Terraform.

**Comment by gregwebs** [comment]
It sounds like you are saying the way you want to achieve this is by merging the code into terraform. I have a feeling that may be a long way out from happening right now, but I am definitely supportive of that. I may take a stab at trying to create a data source that does locking when I get a little more concerned about locking.

**Comment by abtreece** [comment]
Some of the Terragrunt features are also features of Terraform Enterprise,
locking in particular. Thus you may find some  opposition to getting them
included in Terraform.

On Aug 10, 2016 11:35 PM, "Greg Weber" <notifications@github.com> wrote:

It sounds like you are saying the way you want to achieve this is by
merging the code into terraform. I have a feeling that may be a long way
out from happening right now, but I am definitely supportive of that. I may
take a stab at trying to create a data source that does locking when I get
a little more concerned about locking.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gruntwork-io/terragrunt/issues/22#issuecomment-239072518>,
or mute the thread

**Comment by dmrzzz** [comment]
As an alternative lower-tech approach, how about letting terragrunt learn the location of my terraform binary from a terragrunt-specific environment variable?  That way I don't have to put terraform on my PATH, which means if I accidentally type terraform instead of terragrunt it won't do anything.

**Comment by brikis98** [comment]
@dmrzzz That's a great idea. It could be done via a command-line flag, env var, or a setting in the `.terragrunt`:

```hcl
terraform = {
  path = "/foo/bar/terraform"
}
```

I'd happily accept a PR for that!

**Comment by dmrzzz** [comment]
PR submitted (hopefully)!  This is my first-ever Go code _and_ my first-ever github pull request, so I apologize for any newbie mistakes.

I chose env var / command-line flag as opposed to a .terragrunt setting because the value is specific to your local workstation and shouldn't be checked into source control.

**Comment by brikis98** [comment]
@dmrzzz PR worked just fine. Nice work and thank you for contributing :)

> I chose env var / command-line flag as opposed to a .terragrunt setting because the value is specific to your local workstation and shouldn't be checked into source control.

Ah, yea, you're right.

**Comment by brikis98** [comment]
#76 Allows you to specify the path to Terraform via an env var or command-line option.
