### ISSUE TITLE
Cannot install local helm chart.

### ISSUE THREAD

**Issue by DavidConnack** [gruntwork-io/terragrunt#2457]
I have a helm_release that looks as follows:
```
resource "helm_release" "karpenter_config" {
  count            = var.enabled ? 1 : 0
  name             = "karpenter-config"
  chart            = "./karpenter-config"
  depends_on = [helm_release.karpenter]
}
```

It fails to install with the following error:
```
module.karpenter.helm_release.karpenter_config[0]: Creating...
╷
│ Error: could not download chart: path "./karpenter-config" not found
│ 
│   with module.karpenter.helm_release.karpenter_config[0],
│   on karpenter/main.tf line 20, in resource "helm_release" "karpenter_config":
│   20: resource "helm_release" "karpenter_config" {
│ 
╵
ERRO[0018] Terraform invocation failed in /home/david/Projects/Opsfleet/labs-terraform/labs/development/aws/opsfleet_test_task/eu-west-1/dev/eks-addons/.terragrunt-cache/zeh_ClcyDwv4OfjxTtYaPGv91nY/Wia5ry-57_wSt4qxvOKsx5czgFM/templates/eks-addons  prefix=[/home/david/Projects/Opsfleet/labs-terraform/labs/development/aws/opsfleet_test_task/eu-west-1/dev/eks-addons] 
ERRO[0018] 1 error occurred:
        * exit status 1

```
This is only happening with a local chart. Releases using a remote repository work correctly.
As far as I can see, this is not an issue with Terrafrom itself.
Perhaps something to do with how the relative paths are handled by Terragrunt?

**Comment by denis256** [comment]
Hi,
I suspect that the directory `karpenter-config` is not referenced correctly, I think should be used `${path.module}` since during execution TF modules are downloaded and used from `.terragrunt-cache`:

```
resource "helm_release" "karpenter_config" {
  count            = var.enabled ? 1 : 0
  name             = "karpenter-config"
  chart            = "${path.module}/karpenter-config"
}

```

References:
https://developer.hashicorp.com/terraform/language/expressions/references#filesystem-and-workspace-info

Simplified example:
https://github.com/denis256/terragrunt-tests/tree/master/local-helm-chart
https://github.com/denis256/terraform-test-module/blob/master/modules/helm-module/main.tf#L23

**Comment by DavidConnack** [comment]
@denis256 
You Sir are a legend.
Thank you, that worked perfectly.
