### ISSUE TITLE
Hide terragrunt output

### ISSUE THREAD

**Issue by shaharmor** [gruntwork-io/terragrunt#246]
Is there a way/flag to disable terragrunt output and only see terraform output?

**Comment by brikis98** [comment]
Currently, no, but we should move Terragrunt to a better logger (e.g., logrus) that lets us control log levels. In the meantime, you could redirect `stderr` to `/dev/null`, since Terragrunt does all of its logging to `stderr`. However, any logging from Terraform itself that goes to `stderr` would also be lost...

**Comment by shaharmor** [comment]
At the mean time I"ll just do something like this: `terragrunt plan 2>&1 | grep -v 'terragrunt'`

**Comment by rossigee** [comment]
Not all of its logging goes to `stderr`...

```
bash-3.2$ terragrunt output Instance_ID 2>/dev/null
[INFO] Getting version from tgenv-version-name
[INFO] TGENV_VERSION is 0.25.5
...
```

**Comment by slon** [comment]
@brikis98 I would like to create PR for this issue. Do you have any particular preferences for logger?

 While it is possible to go with logrus, another possibility would be switching to github.com/hashicorp/go-hclog, which is used by terraform itself and by terraform providers ([at least in v2 api](https://github.com/hashicorp/terraform-plugin-sdk/blob/master/plugin/serve.go#L59-L70)). go-hclog would require less changes, as it is based on standard logger. It should make logging more consistent as well.

**Comment by brikis98** [comment]
I don't have too strong of an opinion on Go logging libraries. logrus seems much more popular and we use it elsewhere, but I'm not dead set on it. @yorinasub17 @infraredgirl @bwhaley Any of you have strong opinions on Go logging?

**Comment by infraredgirl** [comment]
No strong opinion here.

**Comment by bwhaley** [comment]
Same - no strong opinion on my side. `go-hclog` is consistent with Terraform so that seems like a sensible choice.

**Comment by brikis98** [comment]
OK, given that no one has too strong of an opinion here, I'll make the call that we should go with logrus. Reasoning:

1. It's way more popular than `go-hclog`.
1. We already use it in https://github.com/gruntwork-io/gruntwork-cli, and we hope to move Terragrunt to use `gruntwork-cli` under the hood.

**Comment by brikis98** [comment]
You can now set the log level: https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-log-level

**Comment by vaibhavkhurana2018** [comment]
@brikis98 I can still see o/p related to TG_Env as mentioned in this comment: https://github.com/gruntwork-io/terragrunt/issues/246#issuecomment-731092784

While adding the flag did worked perfectly fine for logs like `No double-slash (//) found in source URL` but the version name is adding on every terragrunt run.

Since this o/p is colored this is interfering with Atlantis, and not giving a colored response while publishing it to git as comment.

**Comment by vaibhavkhurana2018** [comment]
Figured out these logs are coming from TGENV utility and not directly from terragrunt. https://github.com/cunymatthieu/tgenv/blob/dd720f62051bb748f75eee2d83d6768171d45830/libexec/tgenv-exec#L20

**Comment by brettcave** [comment]
There should be a way to control this. 

```terragrunt graph-dependencies | dot -Tsvg > graph.svg
Error: <stdin>: syntax error

terragrunt graph-dependencies | grep -vi 'tfenv' | dot -Tsvg > graph.svg
# no error
```

`TGENV_SILENT=true` would be great, or only output that stuff if TGENV logging is enabled by default is even better.
