### ISSUE TITLE
AWS Auth Doc - IAM - remove s3 object level actions for bucket resource

### ISSUE THREAD

**Issue by Kiran01bm** [gruntwork-io/terragrunt#2532]
The [AWS Auth Documentation page here](https://terragrunt.gruntwork.io/docs/features/aws-auth/#aws-iam-policies) contains s3 object level actions (SID:`AllowCreateAndListS3ActionsOnSpecifiedTerragruntBucket`) such as `GetObject` and `PutObject` on the s3 bucket resource which is not required.

**Comment by denis256** [comment]
I tested it on my environment, and removing `GetObject/PutObject` for `"Resource": "arn:aws:s3:::BUCKET_NAME"` don't cause any issues

**Comment by lorengordon** [comment]
This is because `GetObject` and `PutObject` are object-level actions. But the resource in the statement is the bucket. Bucket actions and object actions use different resource arns. The second statement `AllowGetAndPutS3ActionsOnSpecifiedTerragruntBucketPath` includes `GetObject` and `PutObject` for object-level resources...

**Comment by zackproser** [comment]
@lorengordon :+1: Thank you, makes sense.
