### ISSUE TITLE
S3 bucket ownership update

### ISSUE THREAD

**Issue by denis256** [gruntwork-io/terragrunt#2539]
> Starting in April 2023, Amazon S3 will change the default settings for S3 Block Public Access and S3 Object Ownership (ACLs disabled) for all new S3 buckets

This change is affected creation of S3 buckets by Terragrunt

Integration tests:
```
TestTerragruntSetsAccessLoggingForTfSTateS3BuckeToADifferentBucketWithGivenTargetPrefix
TestTerragruntSetsAccessLoggingForTfSTateS3BuckeToADifferentBucketWithDefaultTargetPrefix
```

References:

- https://docs.aws.amazon.com/AmazonS3/latest/userguide/create-bucket-faq.html
- https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html

**Comment by josh-padnick** [comment]
For those searching GitHub Issues, here's the error we began seeing in Terragrunt build logs:

```
=== CONT  TestTerragruntSetsAccessLoggingForTfSTateS3BuckeToADifferentBucketWithDefaultTargetPrefix
    integration_test.go:3863: Failed to run Terragrunt command 'terragrunt validate --terragrunt-non-interactive --terragrunt-config /tmp/terragrunt-test2536741697/remote_terragrunt.hcl --terragrunt-working-dir fixture-regressions/accesslogging-bucket/no-target-prefix-input' due to error: *s3err.RequestFailure AccessControlListNotSupported: The bucket does not allow ACLs
        	status code: 400, request id: <redacted>, host id: <redacted>
```

The recurring error we've seen a few reports of seems to be "The bucket does not allow ACLs."

Copy/pasting from my colleague @MoonMoon1919:

"Amazon is rolling out a change for the default bucket ownership mode to not allow ACLs. It's being rolled out granularly so it's sporadically failing for tests that don't specify an ACL (since the default is now `BucketOwnerEnforced` instead of `ObjectWriter`)."
