### ISSUE TITLE
Terragrunt precommand

### ISSUE THREAD

**Issue by joshmyers** [gruntwork-io/terragrunt#256]
Afternoon folks,

We currently have a load of Makefiles wrapping all of our Terraform, to do what Terragrunt now does e.g. make scratch dir, copy things in, override etc

We would like to move to Terragrunt as it now supports all this functionality and would have a big win for things like DRY'ing up our code base, `plan-all` etc. All good stuff and we are having good success moving things over. 

I'm having problems with one aspect though and wanted to check:

a) If there are better work around options
b) Propose a work around

Our current Makefile targets have some pre targets to run arbitrary scripts. An example could be a script to check if an SSH key pair exists already, if not create it and store the private key somewhere. We need to be able to do things like this if we are to completely move over to Terragrunt. My first pass at this looked something like:

```
extra_arguments "create_ssh_key_pair" {
      commands = [
        "apply"
      ]

      arguments = [
        "-var", "key_pair_name=$$(scripts/gen-ssh-keypair.sh -c foo_keypair)"
      ]
}
```

As suspected this didn't work as it is passed as a string in the [shell package](https://github.com/gruntwork-io/terragrunt/blob/master/shell/run_shell_cmd.go#L33)

Without wrapping Terragrunt in another script (which is what we are trying to get away from), is there another way to do this that I am missing?

If not, I am wondering if folk think something like a `pre_command` Terragrunt optional block would be useful? I could see it being used something like:

```
pre_command "create_ssh_key_pair" {
      commands = [
        "apply"
      ]

      arguments = [
        "scripts/gen-ssh-keypair.sh -c foo_keypair"
      ]
}
```

**Comment by josh-padnick** [comment]
Hi Josh,

I have a few thoughts for you:

**1. How We Handle SSH Keys at Gruntwork**

We wrote a tool we use with clients called `ssh-iam` that is specific to AWS and allows you to grant SSH access to an EC2 Instance by adding an IAM User to a specific IAM Group. Separately, the IAM User can upload her public SSH Key to her IAM User account. Then, when the user goes to SSH to an EC2 Instance, we've configured `sshd` to run a local binary that fetches the public SSH Keys for that IAM User if and only if that IAM User is in the right IAM Group.

We still create EC2 Keypairs as an emergency backup option, but this way we don't need to create that many of them since most keys are now managed by the IAM Users themselves.

**2. How We Auto-Generate Keypairs**

The short version is that we use a proprietary tool internally to run a script that creates the EC2 Keypair and puts it somewhere when we're creating Terraform code for a client, so this sounds pretty similar to what you're doing. 

We don't need our Terraform/Terragrunt workflows to do this because it's handled in the workflow we use to generate Terraform code. This doesn't solve your problem, but I wanted to share how we solve this.

**3. How You Could Achieve this in Terraform.**

One option is to to use a [Terraform local-exec provisioner] that runs a script on your local machine every time it's invoked. The script should be idempotent so that running it multiples times gives the same end result -- the key exists. If you want to control what "triggers" a re-run of the script, consider using  a [Terraform null resource](https://www.terraform.io/docs/provisioners/null_resource.html) with the [triggers](https://www.terraform.io/docs/provisioners/null_resource.html#triggers) argument specified.

The major downside of this approach is that now everyone who runs your Terraform code has to have the script referenced by your `local-exec` provisioner in the exact same location. 

All of the above being said, the "pre-command" block is an interesting idea. But as a starting point, I'm curious if any of the above solves your problem?

**Comment by joshmyers** [comment]
Thanks for getting back to me @josh-padnick 

1) Sounds interesting, but doesn't fit our current workflow. `ssh-iam` does look super nice, but I was hoping not to have to shave that yak at the same time.

2) We want to get away from wrapper scripts, which is a large reason for moving towards Terragrunt. As Terraform has more features added, being able to run bare terraform commands (albeit through Terragrunt) is a big plus, without some "remember to run this script first" docs

3) Yeah, I thought about `null_resource` trigger to `local-exec`, as we use this pattern already. The problem is that I can see this ending up not being very DRY, things like a call to AWS per instance that the trigger relies on before returning key already exists etc.

A one shot, run this thing before these commands seems to be a better fit, for me anyway. I have something working, needs some tests. Would this be something potentially useful for Terragrunt as a whole?

**Comment by brikis98** [comment]
> Yeah, I thought about null_resource trigger to local-exec, as we use this pattern already. The problem is that I can see this ending up not being very DRY, things like a call to AWS per instance that the trigger relies on before returning key already exists etc.

Can you give an example of why this isn't DRY?

I'd be tempted to argue the opposite: if you need to perform some action for each EC2 Instance, you're better off having that action executed in the Terraform code, so as you update that Terraform code, you remember to update the action too. If it's in a totally separate script, then when you go from, say, 5 EC2 Instances to 10, you might forget to update the action to run 10 times. Also, for some use cases, the [external data source](https://www.terraform.io/docs/providers/external/data_source.html) may be an even better fit than a `local-exec` provisioner.

**Comment by joshmyers** [comment]
Doh, sorry I thought I'd responded to this already, but hadn't submitted. 

This would mainly not be DRY due to our somewhat legacy Terraform codebase. Not as much use of modules as we could etc. I do agree with your point about this particular example of SSH keys better matching the cadence of instance life cycle. I hadn't come across the external data source before (strange thing) but it got the job done. Saying that and before I went down the external data source route, I have some Terragrunt code on a branch that was working executing `pre_commands` with config tests but no integration tests yet.Is this something Terragrunt could be interested in?

**Comment by brikis98** [comment]
I'd be curious to see a PR for it! While I suspect for most things, using Terraform directly as much as possible is likely a safer route, I'm sure there will be other cases where a pre or post command would be handy. Thanks!

**Comment by brikis98** [comment]
Closing in favor of https://github.com/gruntwork-io/terragrunt/issues/377
