### ISSUE TITLE
Terragrunt is not picking assume ec2 role

### ISSUE THREAD

**Issue by zerolaser** [gruntwork-io/terragrunt#259]
How to set terragrunt to use assume ec2 role instead of taking the default credentials from the ~/.aws/credentials ?

**Comment by josh-padnick** [comment]
You actually don't set the source of AWS credentials using Terragrunt. This behavior is programmed into the AWS SDK for Golang, which uses a [hierarchy of authentication methods](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html). In short, if you define a default profile at `~/.aws/credentials`, then the SDK will use those credentials instead of the ones available through the EC2 Instance's IAM Role.
