### ISSUE TITLE
Executing plan with hidden directory fails

### ISSUE THREAD

**Issue by dave-lyric** [gruntwork-io/terragrunt#264]
I suppose this may or may not be a bug, depending on your point of view.

## Description
Executing `terragrunt plan` against a configuration that requires a hidden directory fails because the hidden directory is not copied to the working directory.

## Steps
1. Create a configuration that requires a hidden directory. In my case, I am attempting to create a Nomad job for an agent that has HTTPS enabled. (See Nomad's [Encryption](https://www.nomadproject.io/docs/agent/encryption.html) documentation for details.)

	```
	resource "nomad_job" "job" {
	  jobspec = "${data.template_file.job.rendered}"
	}
	```

1. Set the `NOMAD_CACERT` environment variable.

	```
	$ export NOMAD_CACERT=.ssl/ca.pem
	```
	
1. Run the Terragrunt command.

	```
	$ terragrunt plan
	```

## Expected result

The plan output. Instead, I receive an error:

```
Error running plan: 1 error(s) occurred:
	
* provider.nomad: failed to configure Nomad API: Error loading CA File: open .ssl/ca.pem: no such file or directory
```

## Workaround

Two workarounds that I can see.

1. Copy the cert to the temporary directory.

```
$ cp -r .ssl /var/folders/1f/x60208f52bv2y2w53_h_pxth0000gn/T/terragrunt/4m5kqybpDM3aaDXlxG3CfuMrXNY/QltMrwpCerDYHpcQxM9XyMTnkMs/nomad/nomad-jobs/.ssl
```

2. Export the full path to `NOMAD_CACERT`.

```
$ export NOMAD_CACERT=~/projects/infrastructure-live/src/sandbox/apps/demo-server/.ssl/ca.pem
```

**Comment by brikis98** [comment]
Ah, that's because the `CopyFolderContents ` method intentionally skips hidden files and folders: https://github.com/gruntwork-io/terragrunt/blob/1b0cb787c0314681e92f5ff083486eb5a988452f/util/file.go#L132. That's intentional to avoid copying `.git`, `.terraform`, and other code that you probably don't want copied. 

Out of curiosity, why do you keep that file in a hidden folder? Storing secrets in plaintext in a hidden folder is no more secure than in a normal folder...

**Comment by dave-lyric** [comment]
I see. Well, tbh I inherited it that way. Now that I know this is intentional, I'll make some changes to get it to work.

**Comment by brikis98** [comment]
Ah, got it. Thanks for following up!
