### ISSUE TITLE
Terragrunt run-all evaluates locals of not included modules when --terragrunt-strict-include is used

### ISSUE THREAD

**Issue by MichalKoziorowski-TomTom** [gruntwork-io/terragrunt#2860]
# Terragrunt run-all evaluates locals of not included modules when --terragrunt-strict-include is used

**Comment by denis256** [comment]
For reference:
https://github.com/gruntwork-io/terragrunt/blob/v0.54.12/configstack/module.go#L59
https://github.com/denis256/terragrunt-tests/tree/master/issue-2860

**Comment by egorksv** [comment]
Any news on this? It breaks the entire deployment as in our case staging has no key to production sops file and vice versa

**Comment by MichalKoziorowski-TomTom** [comment]
Hi. Are there any news with PR for this bug? I have really ugly workarounds in my TG modules because of this (filling not needed env variables with fake values in unrelated modules).

**Comment by egorksv** [comment]
https://gist.github.com/egorksv/65ab1a1ab8bc5cfdb7b3a6330e90b5af

Workaround script to force include specific modules

`group/*.hcl` are empty hcl file that are used to logically group modules

**Comment by MichalKoziorowski-TomTom** [comment]
I just started to see "new" version of this bug. 
- If not included module evaluates locals, deployment fails.
- If not included module evaluates inputs, I see errors but deployment continues.
In effect, I need to to provide to terragrunt env variables of modules which I don't want to deploy.

**Comment by amirasyraf** [comment]
Hi, regarding the PR https://github.com/gruntwork-io/terragrunt/pull/3012

Just a question, would it also address dependency evaluation of the terragrunt stack?

For my use case, I append a `.skip` to the path name to environments or stacks we intend to skip. e.g. rename `uat/` to `uat.skip/`. I use `--terragrunt-include-dir` along with `--terragrunt-strict-include` to specify exactly which stacks to execute. My pipeline checks for this path and handles it automatically.

However, since Terragrunt currently does not fully respect the `--terragrunt-include-dir` and `--terragrunt-strict-include`, when another stack which `uat.skip/` depends on gets executed (e.g. networkhub), it will fail because the stacks inside `uat.skip/` are still trying to evaluate the original path `uat/`.

e.g. `uat.skip/tgw` depends on `networkhub/tgw`. So when running `terragrunt run-all plan --terragrunt-strict-include --terragrunt-include-dir networkhub/tgw`, it still evaluates `uat.skip/tgw` - in my case causing a failure as the stacks under `uat.skip` are looking for the original `uat` path.

It really should fully respect the strict flags and not even evaluate it in the first place

**Comment by MichalKoziorowski-TomTom** [comment]
Hi @denis256.
I see that there is a draft PR attached to this issue. Do you maybe plan to have this finished?
