### ISSUE TITLE
Proper integration with VSCode

### ISSUE THREAD

**Issue by kalote** [gruntwork-io/terragrunt#2931]
**Describe the solution you'd like**
I would like to have a syntax highlighting and a nice view in my IDE when I edit a terragrunt file.

**Describe alternatives you've considered**
I was looking at a lot of VS Code extensions, and I haven't been able to find one that manage the `.hcl` file correctly.

**Additional context**
Working with Terragrunt + Terraform is a somehow common practice, and it really works well.
However, the devEx is horrible: nothing is recognized correctly, so many problems, no auto-completion, a lot of red underlined stuff on my screen (see screenshot below)

![Screenshot 2024-02-06 at 10 24 29](https://github.com/gruntwork-io/terragrunt/assets/2253470/165e2aca-ea11-4c50-8163-f3efc0330d75)

Is there an existing solution? I cannot be the only one with this issue =/

Thanks for any suggestions 🙏

**Comment by kalote** [comment]
Looks better indeed 👍

**Comment by josh-padnick** [comment]
@denis256 Any reason we've left this open? Are you thinking that it relates to https://github.com/gruntwork-io/terragrunt/issues/2779? Perhaps it's enough to close this issue now that the two are linked?

**Comment by denis256** [comment]
Closing as resolved

**Comment by jmreicha** [comment]
This one doesn’t appear to do hclfmt formatting on save. Has anyone found a solution for this?

**Comment by josh-padnick** [comment]
FYI, https://marketplace.visualstudio.com/items?itemName=gruntwork.terragrunt-ls doesn't appear in Cursor. The issue appears to be that since Cursor is a fork of VSCode, it pulls extensions from https://open-vsx.org/, which doesn't currently list Terragrunt. Can we fix?

<img width="3844" height="2054" alt="Image" src="https://github.com/user-attachments/assets/253cda46-41b4-4f6e-bc95-b8ba77dc64ae" />

**Comment by yhakbar** [comment]
We can add an issue for this in the https://github.com/gruntwork-io/terragrunt-ls repo.
