### ISSUE TITLE
Assets not part of release `v0.55.8`

### ISSUE THREAD

**Issue by FabianPi** [gruntwork-io/terragrunt#2963]
**Describe the bug**
Unable to download assets from Release [v0.55.8](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.55.8)

**Expected behavior**
Assets are attached to release

**Nice to have**
- [ ] Terminal output
- [x] Screenshots

**Versions**
- Terragrunt version: [v0.55.8](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.55.8)

<img width="1125" alt="image" src="https://github.com/gruntwork-io/terragrunt/assets/1639067/c077e539-339f-465b-9719-71b06c9226ff">

**Comment by oallauddin** [comment]
Failed on downloading. https://github.com/gruntwork-io/terragrunt/releases/download/v0.55.8/terragrunt_linux_amd64 
I guess there will be a new release soon.

**Comment by yhakbar** [comment]
Sorry about that! Investigating.

**Comment by yhakbar** [comment]
Re-running the failed release process successfully released the assets to the release.

It seems like the root cause was a flaky test that caused the builds to fail to complete. We might want to change how the release process handles failed tests, and update release documentation to recommend pre-releases as a way to ensure that assets are fully available before the new release is marked ready.

I'll follow up with @denis256 to make sure that I followed the release process correctly.

Sorry again for the inconvenience everyone!

![Screenshot 2024-02-22 at 7 07 51 PM](https://github.com/gruntwork-io/terragrunt/assets/11247449/354f4c8e-634e-43f5-b983-f5a7b2c38cd2)

**Comment by FabianPi** [comment]
All good now, thanks @yhakbar!
