### ISSUE TITLE
Terragrunt version: 'v0.59.0' causes blob doesn't exist error

### ISSUE THREAD

**Issue by meaganramey** [gruntwork-io/terragrunt#3195]
## Describe the bug

This error was previously seen in version v0.58.10 and was resolved. It appears it has been re-released in version 0.59.0. In that broken version the version was missing the complied binaries.

https://github.com/gruntwork-io/terragrunt/issues/3159

## Steps To Reproduce

Our code : 
```
            LATEST_URL=$(curl -sL  https://api.github.com/repos/gruntwork-io/terragrunt/releases  | jq -r '.[0].assets[].browser_download_url' | egrep 'linux.*amd64' | tail -1)
            curl -sL ${LATEST_URL} > /usr/local/bin/terragrunt
            chmod u+x /usr/local/bin/terragrunt
            terragrunt --version
```

Result: 
```hcl
/usr/local/bin/terragrunt: line 1: syntax error near unexpected token `<'
/usr/local/bin/terragrunt: line 1: `﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.'
```

## Expected behavior

The pipeline should be able to download and run terragrunt and cannot.

## Nice to haves

- [x] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: v0.59.0

**Comment by yhakbar** [comment]
Thanks for reporting this, @meaganramey . Taking a look!

**Comment by yhakbar** [comment]
We've recreated the release, which has side-stepped the issue where the asset is successfully uploaded, but inaccessible via the blob storage mechanism used by GitHub. Thanks again for reporting this so quickly, @meaganramey !

We are investigating ways to automatically detect issues like this and remediate them so that they're not encountered in the wild. We apologize for the inconvenience.
