### ISSUE TITLE
How to use a unique cache server with the provider caching feature?

### ISSUE THREAD

**Issue by Smana** [gruntwork-io/terragrunt#3231]
Hi all,

We've a workflows which runs multiple plans.
I'm wondering if that'd be possible to instantiate just once the caching server and how to do so?
What commands or tools allows to have a single server which stays up until I decide to shut it down?

Thank you and have a nice day.

**Comment by tinder-tder** [comment]
set `TERRAGRUNT_PROVIDER_CACHE_TOKEN` and it should work the way you want.

https://github.com/gruntwork-io/terragrunt/issues/3076

**Comment by Smana** [comment]
Ok thanks @tinder-tder , I understand that setting this env var will prevent issues when using parallel runs. 
However does it answers my question: How to run the cache server once (avoid to start listening on localhost each time a terragrunt command is ran).

**Comment by levkohimins** [comment]
Hey @Smana, 
I understand that you want to be able to run the provider's caching server standalone and then just connect to it. I like that idea. I'll implement it as soon as I find time for this.

**Comment by erpel** [comment]
If this were possible, I imagine we could add such a caching server to the pods running atlantis for our repos. Would be really great in that use case too.

**Comment by yhakbar** [comment]
Hey folks! 

There are a lot of considerations to be had in creating a new feature like a standalone cache server that requires careful consideration. Knowing what commands we'd have to introduce to Terragrunt, how the two would connect, etc all require documentation and a plan.

If possible, please propose a formal RFC for this behavior detailing all of those things so that there's a well designed feature added here. We may not be able to get to it immediately, but if the proposal details the work well, we can approve it and encourage a member of the community to submit a proposed implementation.

I'm going to close this ticket out for now, anticipating a follow-up RFC for a detailed proposal.

Thanks!
