### ISSUE TITLE
Ability to manipulate workspaces in all subdirectories

### ISSUE THREAD

**Issue by crielly** [gruntwork-io/terragrunt#329]
One of the features I find most useful about Terragrunt is the ability to apply-all. It would be very nice to be able to do the same with workspaces.

Use case would be to `terragrunt workspace-all new` to create a new workspace in each subdirectory. Due to Terragrunt also enabling interpolation of vars into backend definitions, this could effectively create a pre-linked set of named workspaces which already know how to pull data from one anothers' backends. Likewise with select and delete.

**Comment by brikis98** [comment]
Pretty good idea.

I wonder if instead of adding `-all` commands one by one, if we shouldn't take a new approach: a `--terragrunt-all-submodules` flag that you can add to *any* command to tell Terragrunt to apply it to all submodules. E.g., Instead of `terragrunt apply-all`, we'd have `terragrunt apply --terragrunt-all-submodules`.

**Comment by jpooler-r7** [comment]
Like @crielly I'm excited to leverage the apply-all functionality of terragrunt but also want to be able to leverage terraform workspaces in our infrastructure.

I started on this but it may be outside my capabilities. I added the CLI args but I've got an idea of where to go next. I'm working here: https://github.com/jpooler-r7/terragrunt/commit/ce987b91cdf65bf8dddc899a75c93f6ee9c6f369

I think  the next steps would be to add options to the configstack/stack.go file to be able to accept a workspace parameter to apply to each submodule? I'm happy to pair on this if anyone has time.

**Comment by brikis98** [comment]
@jpooler-r7 There are quite a few things to do there, but roughly speaking:

1. Update [runCommand](https://github.com/gruntwork-io/terragrunt/blob/master/cli/cli_app.go#L192) to check for the `--all` flag and call `runMultiModuleCommand` if it's there.
1. Update [runMultiModuleCommand](https://github.com/gruntwork-io/terragrunt/blob/master/cli/cli_app.go#L448) to take the first arg (e.g., `plan`, `apply`, etc) and pass it through to `configstack`.
1. Update `configstack` so instead of separate `applyAll`, `planAll`, etc methods ([example](https://github.com/gruntwork-io/terragrunt/blob/master/configstack/stack.go#L72)), it has a single `all` method that takes the command to run as an argument. 
1. Make sure the `all` method calls `RunModules` or `RunModulesReverseOrder` depending on the command.
1. Add tests for all this in `integration_test.go`.

**Comment by stonefury** [comment]
I'm using workspaces, but I wanted terragrunt to allow me to break my large tf project into multiple components.  How can terragrunt help me here?  I need to use workspaces.

**Comment by brikis98** [comment]
Generally, Terragrunt is used as an _alternative_ to workspaces, so I'm not sure of a good way to make the two work together.

**Comment by brikis98** [comment]
Closing in favor of https://github.com/gruntwork-io/terragrunt/issues/492
