### ISSUE TITLE
Terragrunt generated block evaluation

### ISSUE THREAD

**Issue by RTS651** [gruntwork-io/terragrunt#3343]
## Describe the bug
Generate blocks used to create .tf files (tested with providers, backend) from terragrunt.hcl are not evaluated on first _terragrunt init_ command but the files are properly generated.

## Steps To Reproduce
create directory structure

\---project
|-----terraform
|-----terragrunt
|---------terragrunt.hcl

contents of terragrunt.hcl:
```hcl
terraform {
  source = "${get_terragrunt_dir()}/../terraform//"
}

generate "providers" {
  path      = "${get_terragrunt_dir()}/../terraform/providers.tf"
  if_exists = "overwrite"
  contents  = <<EOF
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.101.0"
    }
  }
}
EOF
}
```

_cd ...../project/terragrunt
terragrunt init_

On first init run latest provider is downloaded ignoring version in generated providers.tf

follow up _terragrunt init_ results in error
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider
│ hashicorp/azurerm: locked provider registry.terraform.io/hashicorp/azurerm
│ 3.102.0 does not match configured version constraint ~> 3.101.0; must use
│ terraform init -upgrade to allow selection of new versions
╵
running terragrunt init -upgrade finally downloads specified provider version as expected

## Expected behavior

Generated block create files before terragrunt downloads the tf files to cache and runs init after they are in cache.

(Or am I missing the point of generated blocks in terragrunt ?)

## Nice to haves

- [ ] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: v0.66.3 (v0.55.1)
- OpenTofu/Terraform version: v1.9.4 (v1.5.7)
- Environment details (Ubuntu 20.04, Windows 10, etc.): Windows 11

**Comment by yhakbar** [comment]
Hey @RTS651 ,

I think you might be misunderstanding how Terragrunt works.

When you specify a block like that:
```hcl
terraform {
  source = "${get_terragrunt_dir()}/../terraform//"
}
```

What you're telling Terragrunt is "Terragrunt, I've got a reusable module at `${get_terragrunt_dir()}/../terraform`. Grab that, and use it here. I might ask you to do some other stuff too.

What you're doing with this:

```hcl
generate "providers" {
  path      = "${get_terragrunt_dir()}/../terraform/providers.tf"
  if_exists = "overwrite"
  contents  = <<EOF
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.101.0"
    }
  }
}
EOF
}
```

Is saying "Terragrunt, I know I said that there is a reusable module at `${get_terragrunt_dir()}/../terraform` that I wanted you to fetch and use here, but it needs a bit more, because I don't want to specify a `providers.tf` file inside of it. Instead, could you just generate a `providers.tf` file when you fetch it so that I don't have to store that in the module?"

This, for example is very similar to what you wrote:

```hcl
terraform {
  source = "${get_terragrunt_dir()}/../terraform"
}

generate "providers" {
  path      = "providers.tf"
  if_exists = "overwrite"
  contents  = <<EOF
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.101.0"
    }
  }
}
EOF
}
```

If you run that locally, I imagine it'll work. Notice that the `path` is set to just `providers.tf` for the `generate` block.

That tells Terragrunt to inject a file named `providers.tf` into the directory where it copies the module. That directory can be found nested under the `.terragrunt-cache` directory next to the `terragrunt.hcl` file.

Hopefully that helps! Feel free to re-open this issue if it hasn't.
