### ISSUE TITLE
Docs for older releases

### ISSUE THREAD

**Issue by oallauddin** [gruntwork-io/terragrunt#3478]
## Describe the enhancement

I am not sure if this available or not.  Is there a link to view the docs for older releases?  
https://terragrunt.gruntwork.io/docs/ takes us to the latest docs.  

If I wanted to access the docs for v0.58.2.  Is there a way to get to that?  
Something like.  https://terragrunt.gruntwork.io/docs/v0.58.2

**Comment by yhakbar** [comment]
Hey @oallauddin ,

Unfortunately, the Terragrunt maintainers do not have the bandwidth to maintain multiple sets of accurate live documentation at once.

The best I can offer you is to check out this repo at the tag you want, then spin up the docs server locally:
https://github.com/gruntwork-io/terragrunt/tree/main/docs

I make no guarantees that it will spin up correctly. You may have to do some debugging to get it to work right.

Please share if there's something that can be done to help you upgrade to the latest version of Terragrunt so that you don't need to do this.
