### ISSUE TITLE
Seeking Best Practices for Proper Use of Catalog, Scaffold, and Boilerplate Together

### ISSUE THREAD

**Issue by brant4test** [gruntwork-io/terragrunt#3674]
Hi Team,

Here are a few questions to confirm. Thank you.

1. I know `terragrunt scaffold` command can scaffold out a MODULE. Can it also scaffold out the reference-architecture blueprints? For example, can we run `terragrunt scaffold` command to invoke the reference-architecture blueprint with the given variables like [this](https://github.com/gruntwork-io/boilerplate/blob/9ea2a6ade35049f850a056ad020c9603c0571107/examples/for-production/terragrunt-architecture-catalog/README.md#quickstart)? Or is it that only `boilerplate` command can invoke the reference-architecture blueprints?
2. Can the `terragrunt catalog` command directly render the reference-architecture blueprints?
3. Is it recommended to maintain blueprints under a directory like `examples/for-production/terragrunt-architecture-catalog/blueprints` and to maintain [external templates](https://github.com/gruntwork-io/terragrunt/tree/8806732d40a4cb96388689c57c169494b4e5fac8/test/fixtures/scaffold/external-template) that the `terragrunt scaffold` command can use under a directory like `examples/for-production/terragrunt-architecture-catalog/templates/services`? This way, all templates are maintained in a single repo, except for the [module-with-template](https://github.com/gruntwork-io/terragrunt/tree/8806732d40a4cb96388689c57c169494b4e5fac8/test/fixtures/scaffold/module-with-template).

**Comment by yhakbar** [comment]
The `terragrunt catalog` URLs use normal `go-getter` URLs, and typically the best way to avoid incompatibility with specific platforms is to use a more generic syntax.

For example, instead of using github.company.com for your URL, you might instead use the equivalent HTTPS or SSH URL that you would use when fetching modules.

**Comment by yhakbar** [comment]
You can learn about custom templates for scaffolding [here](https://terragrunt.gruntwork.io/docs/features/scaffold/#custom-templates-for-scaffolding). It boils down to creating a `.boilerplate` directory within the directory where you want to have a custom template for scaffolding, and writing Boilerplate configurations in that directory for the scaffold.

The templates available in `terragrunt-architecture-catalog` are intended to be used directly by boilerplate, and not as part of Terragrunt scaffold. This is because they are typically created in the context where Terragrunt might not be installed (like when bootstrapping a new Terragrunt repository in `infrastructure-live-root`, etc). I wouldn't recommend trying to scaffold those out.

In the future, we may offer ready to use templates similar to them for integration with scaffold, but for now, we only offer first-class support for scaffolding modules as units.

Let me know if that answers your questions! Also, this might be a longer conversation. Feel free to chat with me in [the Terragrunt Discord](https://discord.gg/SPu4Degs5f) or the [Gruntwork.io Slack](https://gruntwork-community.slack.com/archives/CHH9Y3Z62) if this is more of a DevOps Foundations product request than a Boilerplate/Scaffold issue.

**Comment by yhakbar** [comment]
The root cause seems to be that the URL pattern for GitHub Enterprise isn't supported here:
https://github.com/gruntwork-io/terragrunt/blob/d2a0285cc5cf6c797570eb50f3dc1b0863348843/cli/commands/catalog/module/repo.go#L147

We can add extra cases to support that. I'll look to add that soon.
