### ISSUE TITLE
Terragrunt doesn't work correctly with asdf installer

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terragrunt#409]
After installing Terragrunt with `asdf`, the `plan` command fails:

```
> terragrunt plan

[...]

[terragrunt] 2018/01/26 17:40:01 Downloading Terraform configurations from git::ssh://git@github.com/[redacted]/[redacted].git?ref=v0.0.1 into [redacted] using terraform init

[...]

2018/01/26 17:40:01 Running command: terraform init [redacted]
No version set for terraform
[terragrunt] 2018/01/26 17:40:02 exit status 255
```

@tomdavidson Any idea what could cause this? Some sort of sandboxing by asdf?

**Comment by brikis98** [comment]
I've removed the Linux package manager installers from the README for now, since they both seem to have bugs: https://github.com/gruntwork-io/terragrunt/commit/beb3c8e70eb2c7430ea1b0db32cc14ba5f2c55cf

**Comment by tomdavidson** [comment]
Shoot. Sorry It was not a good experience for you.  I am using it in my CI/CD pipeline and on my workstations, but they are in the Debian family. The asdf terraform plugin has had much broader usage.

> No version set for terraform

Did you set the version either global or local? ie `asdf (global|local) transform 0.11.2` does terraform and terragrunt version return the expect versions?

>  Some sort of sandboxing by asdf?

It installs the binaries outside of your shell's path and then sets aliases based on the $HOME/.tool-versions or $PWD/.tool-versions. I have a Tectonic project that can not use Terraform 0.11.x so that project has a .tools-versions file with 0.10.8 but other projects I am working on are using current. My CI runners use asdf too, so the expected version is always used - not just an installer.

**Comment by brikis98** [comment]
No worries! Bugs happen :)

@jeffutter Could you provide more details on the issue you saw?

**Comment by tomdavidson** [comment]
The [plugin pr](https://github.com/asdf-vm/asdf-plugins/pull/19) has been accepted so it can now be installed without listing the git repo  ie
```shell
$ asdf  plugin-add terragrunt
```

@jeffutter @brikis98  I never heard any details concerning the "bug" - is it a bug if there is no confirmation or details?

**Comment by brikis98** [comment]
@jeffutter If you have a min, it would be great if you could try again with `asdf`. Thx!

**Comment by jeffutter** [comment]
Yeah, sorry for not replying sooner. I think the issue was mostly on my end.

I forgot that I don't usually start asdf with my shell. I just `source /usr/local/opt/asdf/asdf.sh` when I need a specific version of something.

I think what happens then is `asdf` puts it's shims on my `PATH` and sets some other context to know what version of terraform the shims reference.

When `terragrunt` then launches it starts a subshell which preserves the altered PATH but loses whatever the asdf stubs use to tell it what version to use thus `No version set for terraform`. I imagine it would work just fine if I load `asdf` when my shell starts.

**;tldr** An issue with my own setup/workflow. Feel free to close.

**Comment by brikis98** [comment]
Ah, thanks for the explanation @jeffutter! I'll close this issue.

@tomdavidson Would you mind putting the `asdf` instructions back in the docs?
