### ISSUE TITLE
Clarification on Relationship between Modules, Components, and Deploy project

### ISSUE THREAD

**Issue by PlethoraOfHate** [gruntwork-io/terragrunt#491]
I've been using TF for sometime, but have been reading quite a lot about the terragrunt tool and really like what it brings to the table. I have a new project I'm putting together, and I wanted to get some clarification on how to handle the layout and structure therein.

I understand the relationship between using simply tfvar files in the "deploy" project, which is the one I'd run terragrunt against, and the modules project that has the base TF modules in it. I also planned on keeping them in separate repos to take advantage of the versioning and such. However, I'm hoping to get some insight with regard to the middle piece which is "components" (What I've been calling them, and have seen others call them as well)

For example....
Deploy project has a tfvar file which uses source to reference a component, which subsequently references one or more (usually more!!) modules.

* tfvar (deploy project)
  * infrastructure_core (component)
    * vpc (module)
    * subnet (module)
    * NAT (module)
    * etc.

So what I'm trying to understand is sort of multi-level.

* Should I not be using modules in this way, and instead have the TF code that is currently in the modules instead bubbled up to the "components"?
* If I do keep them separated, does it make sense to keep them in separate repos? (It seems to to me since that would allow another level of versioning)
  * With that in mind, is this really a DRY setup since I can't interpolate the versions through to the modules because of the limitations in TF itself? (i.e. I can control the desired versions strictly with terragrunt and the deploy project)
  * OR....is this still DRY because the development of the components would follow a workflow using pure terraform for testing and such and a specific component version is expected to have been "tested" with the specific module versions therein?

Curious what the thoughts of the community with regard to best-practices are.

**Comment by brikis98** [comment]
> Should I not be using modules in this way, and instead have the TF code that is currently in the modules instead bubbled up to the "components"?

Yup, this is exactly how we do it.

Terraform calls _everything_ a module, even modules that pull in other modules, but I agree that terminology can be confusing. So yes, if we call the top-level things in `infra-modules` "components", then you use Terragrunt in `infra-live` to deploy those components, and those components use a bunch of modules under the hood.

> If I do keep them separated, does it make sense to keep them in separate repos? (It seems to to me since that would allow another level of versioning)

This is the classical trade-off global vs local trade-off (you'll see similar trade-offs with microservices vs monoliths and multi-repo vs monorepo). If you define the underlying modules (e.g., a module for a VPC or DB) in a separate repo, you make local dev easier: with each module isolated, it's easier to maintain that code, write tests for just that one module (and the tests run faster since there's less stuff to test), and version it.  Moreover, with the codebase separate, it forces you to think of more APIs, backwards compatibility, and reuse. As a codebase and team gets larger, these sorts of factors become more and more important. This is what we do with the [Gruntwork IaC Library](https://gruntwork.io/infrastructure-as-code-library/). 

However, global changes are now harder. If you have to change something in many modules or many components (e.g., roll out a security fix), you have to checkout tons of repos, bump lots of version numbers, and figure out how to get it all to work together. Code search and maintaining consistency is harder across multiple repos. And, somewhat by design, you lose continuous integration: you may have made an important fix in some module, but until a team member bumps to that new version, they won't see it, so it's possible they are coding against assumptions that are no longer true.

**Comment by yorinasub17** [comment]
Closing as stale and the question has been answered. If there are still questions/concerns regarding the topic, please open a new issue!
