### ISSUE TITLE
locking terraform state file stored in OCI Object Storage using terragrunt

### ISSUE THREAD

**Issue by tama1214** [gruntwork-io/terragrunt#693]
Hi all,
To locking terraform tfstate file Terragrunt offer to use AWS DynamoDB. In this case Terragrunt use AWS S3 bucket for remote state storage.  But my question is about locking tfstate file stored in OCI (Oracle Cloud Infrastructure) Object Storage. Is it possible to use terragrunt to block tfstate file stored in OCI Ojbect Storage? And if so, how will the code template for terragrunt look in this case?

Thank you in advance.

**Comment by brikis98** [comment]
You can use any of the backends supported by Terraform: https://www.terraform.io/docs/backends/types/index.html. Put whatever configs you would've put in the `backend "xxx" { ... }` block into Terragrunt's `config` block.

**Comment by tama1214** [comment]
@brikis98 , thanks for your reply.  But my question is a little different. 

I'm wondering if there is an **alternative** to AWS DynamoDB in **OCI (Oracle Cloud Infrastructure)**? I can't use AWS DynamoDB to lock the tfstate file. **Is there any tool in OCI that I can use to lock a tfstate file through terragrunt?** Thank you.

**Comment by brikis98** [comment]
Ah, that book is out of date. When Terragrunt first came out, Terraform didn't support locking at all, so we implemented locking in Terragrunt using DynamoDB. Since then, Terraform added its own native locking, so we removed locking From Terragrunt.

So if you want locking, you need to use one of the officially supported backends that supports it: https://www.terraform.io/docs/backends/types/index.html.

**Comment by tama1214** [comment]
oh, many thanks for this information. I will refer to this document. Thanks!
