### ISSUE TITLE
.tf.json files not cleaned up

### ISSUE THREAD

**Issue by victoriaalee** [gruntwork-io/terragrunt#725]
I receive an error when I run subsequent commands after the initial command (`terragrunt plan/apply`). I believe this is because `.tf.json` files aren't cleaned up from `.terragrunt-cache`.

```
The working directory already contains files. The -from-module option requires
an empty directory into which a copy of the referenced module will be placed.

To initialize the configuration already in this working directory, omit the
-from-module option.
```

**Comment by brikis98** [comment]
Ah, good find. Would you be up for a PR to fix this?

**Comment by victoriaalee** [comment]
@brikis98 Moving my comment on #571 to here.

I noticed that in that issue you had mentioned requests for cleaning up all files/folders. I was wondering if this was still desired, and if so, should this be the default behavior?

I did a quick search on the open issues to see if there was any discussion on this, but I wasn't able to find any additional issues that mentioned that request. I don't think I know enough about Terragrunt to know if there would be a use case where you wouldn't want to clean up all files/folders.

**Comment by brikis98** [comment]
I'm scratching my head... I think we don't delete all files to avoid deleting the `.terraform` folder Terraform uses as a cache, so you don't have to download modules, providers, and configure state every time. I can't remember if we avoid deleting other files for some reason off the top of my head though 😕

**Comment by brikis98** [comment]
Oh, you know what, I think the Terraform state file, assuming you're using local state, is one of the items that'll be in that folder... So deleting it outright would be a bad idea.

**Comment by victoriaalee** [comment]
@brikis98 Would a valid approach for cleaning up `.terragrunt-cache` be to delete all files/folders in it except for the `.terraform` folder and `terraform.tfstate`?

I'll see if I can make the fix some time this week.

**Comment by brikis98** [comment]
I was actually just digging through that code in #739 and, unfortunately, it's a bit more complicated. Here's what has to be maintained _that I'm aware of_:

1. `.terraform` folder and its contents. Contains modules, provider code, remote state config.
1. `terraform.tfstate`. Contains local state config.
1. `terraform.tfstate.backup`. Contains local state config backup.
1. `.terragrunt-source-version`. Used by Terragrunt to know if a new version of `source` should be downloaded.

However, it's potentially even trickier. For example, a user could run `terraform apply -state-out=foo` to tell Terraform to store the state in a file called `foo` rather than `terraform.tfstate`. There's also `terraform plan -out=foo` to store a plan file, and possibly other data you don't want to lose. 

So for now, in the [cleanupDownloadDir method](https://github.com/gruntwork-io/terragrunt/blob/master/cli/download_source.go#L332), I just make sure not to delete anything in the working dir other than `.tf` files. Perhaps the easiest fix is to just expand the [glob expression](https://github.com/gruntwork-io/terragrunt/blob/master/cli/download_source.go#L370) to also delete `.tf.json` files?
