### ISSUE TITLE
Enhancement: Support local variables in terragrunt.hcl

### ISSUE THREAD

**Issue by jfunnell** [gruntwork-io/terragrunt#776]
Hi! I have just started using terragrunt and was wondering if anyone other than me would find local vars to be useful in some way.

Personally, I would use them to make my configs more readable.. I currently have the following shared inputs in my root terragrunt.hcl file:
```
  env        = split("/", path_relative_to_include())[0]
  app_region = split("/", path_relative_to_include())[1]
```
which is fine.. but then I need to interpolate those into some other variables, such as aws_region, app_tags, etc etc. and it gets a bit messy to keep using `split(path_relative_to_include())[x]`. Locals would really improve readability, and means I don't need to push the interpolation magic down the stack into the modules.

Additionally, I could see a use case for using locals to cache the output of a `run_cmd` although I don't currently have a need for it. Something like creating a randomly named tempfile and deleting it in a before/after hook pair, for example.

**Comment by brikis98** [comment]
Yes, local vars and ways to reference vars in Terragrunt would be useful in Terragrunt. We also need a solution to a similar variable-handling problem in #752. 

Proposals welcome. Bonus points for finding a minimal set of primitives that provide the power to solve these problems, rather than one-off solutions for each task.

**Comment by yorinasub17** [comment]
It turned out to be relatively straightforward to implement a `locals` attribute that is rendered before the full config, so created a PR here: https://github.com/gruntwork-io/terragrunt/pull/802

This most likely isn't the comprehensive minimal primitive to solve all problems, but I think is useful step forward nonetheless.

**Comment by yorinasub17** [comment]
This is now released: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.14
