### ISSUE TITLE
Terraform 0.12 / Terragrunt 0.19 tfvars Clarification

### ISSUE THREAD

**Issue by jpreese** [gruntwork-io/terragrunt#782]
It seems a little unclear to me on whether or not the intent is to *completely* obsolete tfvar files or not with the releases of Terraform 0.12 and Terragrunt 0.19.

Given the fact that you cannot chain terragrunt.hcl files (using an input block to override set values at multiple levels as you traverse folders), forcing a single parent, my assumption is that the intent was to keep `tfvars` relevant. 

Though the `live` / `module` repos do not have any in their examples.

**Comment by brikis98** [comment]
> It seems a little unclear to me on whether or not the intent is to completely obsolete tfvar files or not with the releases of Terraform 0.12 and Terragrunt 0.19.

No, I don't think that's the intention. 

Terraform 0.12 still uses `.tfvars` files, but one important change is that any variable you set in a `.tfvars` file must be defined in a `.tf` file. As long as that's the case, you can still use `.tfvars`.

Before 0.19, Terragrunt used to have its own config in a `.tfvars` file in a `terragrunt = { ... }` block. However, due to the previously mentioned change in Terraform 0.12, we can no longer do that, so we moved to a `terragrunt.hcl` file. But you can still use `.tfvars` files to pass variables, as mentioned in the previous paragraph.

**Comment by jpreese** [comment]
Ok thanks for the clarification. I didn't see a way around it, but there was any usage in the module/live demo repositories. 

I think there would be value in making that a little more production-y with the inclusion of some variables and how it would look if you added a second region. Right now, I'd be curious how it would look if you added us-east-2. The terragrunt file is hard coded to the east1 region, though you could have multiple regions/folders in that directory.

**Comment by brikis98** [comment]
Agreed the examples could be more extensive. We are buried at the moment, so PRs welcome!

**Comment by jpreese** [comment]
Will do! Thanks
