### ISSUE TITLE
GOOGLE_CREDENTIALS no more since Terragrunt 0.19.6

### ISSUE THREAD

**Issue by fhusson** [gruntwork-io/terragrunt#783]
Hi,

We use the GOOGLE_CREDENTIALS to store the content of the credentials (not the file path)
It worked with previous version of terragrunt, but since the Terragrunt 0.19.6 it doesn't work anymore.

if we use a GOOGLE_APPLICATION_CREDENTIALS var with the file path it works, but we don't want to store the information on the CI/CD runner.

We use a simple remote state with GCS

```
remote_state {
  backend = "gcs"
  config = {
    bucket         = "mybucket"
    prefix         = "myprefix/with/folders"
  }
}
```

**Comment by brikis98** [comment]
@robmorgan @autero1 Could you help out with this one?

**Comment by lawliet89** [comment]
This is because the new GCS Remote State feature [creates](https://github.com/gruntwork-io/terragrunt/blob/5e05e0c1f2aaa79c3cde1e50889bf63cef03dadc/remote/remote_state_gcs.go#L384) GCP Client only using the default [ADC behaviour](https://cloud.google.com/docs/authentication/production#providing_credentials_to_your_application) whereas the Google Terraform Provider has additional [behaviour](https://www.terraform.io/docs/providers/google/provider_reference.html#credentials-1) for obtaining credentials before falling back to ADC. 

`GOOGLE_CREDENTIALS` is one of the additional environment variables that the Google Terraform Provider supports, but is not part of ADC.

**Comment by fhusson** [comment]
Hi, thanks for the response, can we have a backward compatible version with GOOGLE_CREDENTIALS ?

**Comment by eyalzek** [comment]
Any update on this issue?

**Comment by robmorgan** [comment]
hi @fhusson, @eyalzek it would be great if you could help test my PR: https://github.com/gruntwork-io/terragrunt/pull/907. Just checkout the branch and build a custom version of terragrunt: `go build -o terragrunt . && ./terragrunt`. Then try setting the `GOOGLE_CREDENTIALS` environment variable.

**Comment by eyalzek** [comment]
@robmorgan I'm seeing the same error: `Missing required GCS remote state configuration project`.

**Comment by robmorgan** [comment]
hi @eyalzek, can you share your `remote_state` definition? I'm assuming you built the version in my branch `mirror-terraform-gcp-auth`?

**Comment by fhusson** [comment]
We have used a workarround with gitlab ci/cd we have set the GOOGLE_APPLICATION_CREDENTIALS as a file variable, that way the file is only temporary on the runner.
I can try to check the patch in 2 weeks.

**Comment by robmorgan** [comment]
@fhusson roger.

**Comment by yorinasub17** [comment]
Going to reopen until we have confirmation that the latest patch (released as https://github.com/gruntwork-io/terragrunt/releases/tag/v0.20.5) is working.

**Comment by robmorgan** [comment]
Okay

**Comment by yorinasub17** [comment]
Closing this out due to inactivity. Please open a new issue if anyone still experiences problems.
