### ISSUE TITLE
Migrate to terraform 0.12.4 user_data hash issue

### ISSUE THREAD

**Issue by natarov** [gruntwork-io/terragrunt#786]
**Issue:**
After migration to terraform 0.12.4, terragrunt 0.19.8 and aws provider 2.19.0 I've got an issue with user_data hash, it's going to recreate instances as user_data hash has been changed, if I put user_data to lifecycle ignore_changes issue has gone. The issue doesn't relate with aws provider as on terraform 0.11.14, terragrunt 0.18.3 and aws provider 2.19.0 (the same which I use with 12 terraform) I don't have this issue

**Comment by mcalhoun** [comment]
Hi @natarov,

This sounds like it might be a Terraform core or AWS Provider issue rather than a Terragrunt issue. Are you able to do an isolated test with Terraform directly to figure out if the same thing happens with Terragrunt out of the equation?

**Comment by natarov** [comment]
Yes, using terraform directly I've received the same result

**Comment by yorinasub17** [comment]
Hi @natarov, please open this against [the AWS provider repo](https://github.com/terraform-providers/terraform-provider-aws/issues), providing a minimal example using terraform. The provider has 2 completely different code paths between Tf12 and Tf11 even if you are using the same version, so it could still be a bug in the provider.

I am going to close this since this is not an issue with terragrunt.
