### ISSUE TITLE
terragrunt cache file does not update 

### ISSUE THREAD

**Issue by rajeshkrrajjo8** [gruntwork-io/terragrunt#819]
terragrunt cache files are not updated when you try to run a remote terraform resource present in another repository.
After cloning the target repository for the first time, it does no longer clone or if there are any changes in the remote repository, they are updated in the terragrunt cache file.

**Comment by brikis98** [comment]
This is by design. Terragrunt follows the same behavior as Terraform: if you're using a local file path for `source`, you always get the latest code; if you are using a URL, it downloads it once and does not re-download on every run, as that would be way too slow. Generally, URLs are good for immutable, versioned code anyway; if you are doing iterative development with lots of changes, use a local file path (see also `--terragrunt-source`).
