### ISSUE TITLE
[BUG] infinite loop with dependency outputs feature

### ISSUE THREAD

**Issue by jonathancolby-olx** [gruntwork-io/terragrunt#844]
The dependency configuration item was introduced to pass outputs between modules.   It is indeed very useful (thanks for that!!). However,  the `dependency` configuration item also creates a run dependency,  as confirmed in the README (`Note that each dependency is automatically considered a dependency in Terragrunt. `)

This can result in an endless execution loop. 

example.

```
=================
foo/terraform.hcl

dependency "bar" {
  config_path = "../bar"
}

inputs = {
  bar_stuff = dependency.bar.outputs.domain
}

=================
bar/terraform.hcl

dependency "foo" {
  config_path = "../foo"
}

inputs = {
  foo_stuff = dependency.foo.outputs.domain
}

```

The above configuration will cause terragrunt to go back and forth between the two modules, and run terraform outputs endlessly.

A possible enhancement would be to not treat `dependency` as an execution dependency, only as a way to extract terraform outputs

**Comment by brikis98** [comment]
Thanks for the report! We actually already have rudimentary logic to detect cycles, so we probably just forgot to use it when implementing the `dependency` block. @yorinasub17 When you're back from vacation, could you take a look?

**Comment by yorinasub17** [comment]
I'll look into providing a clearer error message for cycles.

---

> A possible enhancement would be to not treat dependency as an execution dependency, only as a way to extract terraform outputs

I'd like to understand your use case for this better. This behavior would be very confusing to me.

The reason why we treat the dependency as an execution dependency is that it doesn't make sense to depend on outputs of the data of something that hasn't been applied. You almost always want to get the "freshest" state of data, or you can get into nasty situations in an `apply-all` where the changes don't propagate correctly. For example, if you have a module that depends on a subnet defined in a VPC module, and you have changes such that the subnet recreates or you have a new subnet, then not treating the dependency lookup as an execution dependency would cause the `apply-all` to possibly finish against the old subnet because of the execution order. Not to mention that execution order matters a lot in the initial deployment with `apply-all`, where you don't have anything deployed.

I have a hard time seeing a use case where you DON'T want to have the "freshest" dependency in an `xxx-all` situation, so it would help if you can share your use case for the above suggestion.

**Comment by yorinasub17** [comment]
Actually, now that I am digging in, I just realized that the issue has nothing to do with execution dependency ordering and instead has to do with the fact that `terragrunt output` goes through the config. So if the config has a dependency block, just running `terragrunt apply` would cause the infinite loop, even when only extracting outputs because you can't extract the outputs unless the config can be resolved, and the config can't be resolved unless all the dependency blocks are resolved.

**Comment by yorinasub17** [comment]
Cycles no longer result in an infinite loop and instead will error out starting in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.23.

Closing this out now. We can reopen if there are compelling use cases where it makes sense to allow cyclic dependencies, and if it can be implemented without making the config parsing logic too complex.
