### ISSUE TITLE
Possible to apply-all without input=false -auto-approve?

### ISSUE THREAD

**Issue by slaughtr** [gruntwork-io/terragrunt#893]
Is it possible to somehow apply-all without the input=false -auto-approve flags being added? I've run into several issues with TG 0.19 and am finding debugging to be particularly frustrating because of this combined with the suddenly extreme amount of `[terragrunt]` logs. Being able to confirm each step would (hopefully) reduce this pain.

**Comment by yorinasub17** [comment]
I think having a way to turn off the auto-approve flags for `terraform` makes sense, although I am not sure if there is an easy way to make the prompts make sense. `terragrunt` runs all of the sub directories in parallel with `apply-all` and thus both the `stdin` and `stdout` is practically useless because you wouldn't know which one is being prompted.

It sounds like what you really want is to run `apply-all` sequentially for debug purposes, and https://github.com/gruntwork-io/terragrunt/pull/636 would be the WIP implementation for that.

**Comment by slaughtr** [comment]
I think that solution would be the correct one. Closing this and watching that one eagerly :) Thank you!
