### ISSUE TITLE
Allow to run downstream layers of excluded layers when using Terragrunt *-all

### ISSUE THREAD

**Issue by JeanFred** [gruntwork-io/terragrunt#905]
When using `exclude-dir`, terragrunt will not run the downstream layers of the excluded layers.

This makes perfect sense for apply-all and destroy-all, however it should not really matter for plan-all since the state is not altered between the plans.

Further to #868, this is a proposal to allow to run the downstream layers of excluded layers anyways.

Our use case is for testing on a CI server:
- because reasons, we cannot plan some layers in CI (insufficient permissions), however we can plan other layers which depend on them.

**Comment by JeanFred** [comment]
@brikis98 I would have some questions.

- Do we want this behaviour to be triggered via the flag introduced in #891, `terragrunt-ignore-dependency-order`? Or another flag?
- I can see two ways of implementing this:
  - in `running_modules.go`, just conditionally avoid the call to `removeFlagExcluded` in `toRunningModules`.
  - avoid flagging the dependant modules in the first place in `module.go`

I lean towards the first option, but checking before starting :)

**Comment by brikis98** [comment]
Just to make sure I understand, you're running `plan-all --exclude-dir foo`... And within folder `foo`, there are several modules, some of which you want to exclude, and some which you don't?

**Comment by JeanFred** [comment]
> Just to make sure I understand, you're running `plan-all --exclude-dir foo`... And within folder `foo`, there are several modules, some of which you want to exclude, and some which you don't?

Not exactly, our infra looks something like:
```
prod
├── app
│   ├── secrets.tfvars.enc
│   └── terraform.tfvars
├── data-store
│   ├── secrets.tfvars.enc
│   └── terraform.tfvars
├── networking
│   ├── secrets.tfvars.enc
│   └── terraform.tfvars
└── terraform.tfvars
```

`app` depends on `data-store` which depends on `networking` (via ` dependencies {    paths = ["../networking"]  }`).

Because of permission reasons (that we hope to solve at some point, but cannot yet), our CI system cannot plan, say, the `data-store` layer (it needs AWS permission that we don’t want to grant ; or it relies on a submodule that we don’t want the CI system to be able to clone, etc.).

I thus want to plan all layers except `data-store`.

Currently, `plan-all --exclude-dir data-store` will exclude `data-store` and `app`, since `app` depends on `data-store`.

The new behaviour would be to run the plan against `app` anyways.

**Comment by brikis98** [comment]
Thx for the explanation!

> Currently, plan-all --exclude-dir data-store will exclude data-store and app, since app depends on data-store.

So when you run `terragrunt plan-all --exclude-dir data-store` in the `prod` folder, it *also* excludes `app`? And I guess that's because `app` depends on `data-store`, so Terragrunt is trying to be conservative, and makes the assumption that if we're not processing `data-store`, we won't succeed in processing anything that depends on it?

Now I think I understand your question here:

> Do we want this behaviour to be triggered via the flag introduced in #891, terragrunt-ignore-dependency-order? Or another flag?

`--terragrunt-ignore-dependency-order` should definitely NOT skip the `app` folder. I'm not convinced we need yet another flag that does that too... Probably best to wait and see if a use case for that comes up, but for now, changes just the `--terragrunt-ignore-dependency-order` behavior.

> I can see two ways of implementing this:

I'm not sure on the best approach, as this code has been updated many times since I last worked on it! I'd recommend doing a TDD style approach here, making sure we have test cases that verify both options: i.e., that `app` is excluded and is not excluded, depending on the `--terragrunt-ignore-dependency-order` flag... And once those tests are passing/failing as expected, try out the two implementation options you considered to see how complicated they turn out to be, and if they pass tests.

**Comment by JeanFred** [comment]
So, I wanted to implement this, and started by adding some tests for `removeFlagExcluded` in its current behaviour. Filed this as #912 

And doing, that I discovered that:

> So when you run `terragrunt plan-all --exclude-dir data-store` in the `prod` folder, it _also_ excludes `app`? And I guess that's because `app` depends on `data-store`, so Terragrunt is trying to be conservative, and makes the assumption that if we're not processing `data-store`, we won't succeed in processing anything that depends on it?

…actually no, `app` is not excluded − I got confused because the pattern I used for excluding the layer I did not want just happened to also match a layer that depended on it ^__^"

So, while an argument _could be made_ that Terragrunt should be conservative and not try to process downstream dependencies of excluded modules, that is not the current behaviour, and that issue is thus invalid :-)

**Comment by JeanFred** [comment]
Hmmm, so that’s for `removeFlagExcluded`.

However, re-reading `module.go` it really seems to me that https://github.com/gruntwork-io/terragrunt/blob/master/configstack/module.go#L128-L133 should mark the dependencies as excluded too… :thinking:

**Comment by JeanFred** [comment]
> However, re-reading `module.go` it really seems to me that https://github.com/gruntwork-io/terragrunt/blob/master/configstack/module.go#L128-L133 should mark the dependencies as excluded too… thinking

But that’s covered by `TestResolveTerraformModulesTwoModulesWithDependenciesExcludedDirsWithDependency` so I guess I’m just missing something ^_^ (sorry for thinking aloud here!)

**Comment by brikis98** [comment]
> However, re-reading module.go it really seems to me that https://github.com/gruntwork-io/terragrunt/blob/master/configstack/module.go#L128-L133 should mark the dependencies as excluded too

It's using canonical paths—i.e., absolute paths with all relative paths resolved—so wouldn't `app` correspond to exactly one path / module on the whole file system?

**Comment by JeanFred** [comment]
> > However, re-reading module.go it really seems to me that https://github.com/gruntwork-io/terragrunt/blob/master/configstack/module.go#L128-L133 should mark the dependencies as excluded too
> 
> It's using canonical paths—i.e., absolute paths with all relative paths resolved—so wouldn't `app` correspond to exactly one path / module on the whole file system?

I have a module called `app` and another called `application-roles` − the latter is definitely excluded when using `--terragrunt-exclude-dir app`

**Comment by brikis98** [comment]
Oh, that must be because it's doing a `string.Contains` check instead of an equality check: https://github.com/gruntwork-io/terragrunt/blob/master/configstack/module.go#L201. That's probably not a side effect we want. Since the `--terragrunt-exclude-dir` supports unix-style globs, it _seems_ like `--terragrunt-exclude-dir 'foo'` should be an exact match on `foo`, whereas `--terragrunt-exclude-dir 'foo*'` should match `foo`, `foobar`, etc...
