### ISSUE TITLE
SSH issues with Windows 10

### ISSUE THREAD

**Issue by JoeWaddingtonWaFd** [gruntwork-io/terragrunt#918]
When a module calls for a remote repo from GitHub, Terragrunt attempts to connect using SSH and download that repo. I am continually getting the error "git@github.com: Permission denied (publickey)."

I can confirm that the key I am using allows me to clone the repo, as well as push to the repo. No credentials other than the SSH key are used. I have deleted and recreated the key numerous times. I am always able to clone the repo with it, but Terragrunt always fails.

I have attempted to both modify and remove the variable GIT_SSH_COMMAND, to address the go-getter issue found [Here](https://github.com/hashicorp/go-getter/issues/187).

If I had to make a guess, Terragrunt is not actually sending the key in my SSH key store. (`ssh-add -L` does list the cert)

**Setup**:
Windows 10 1809
OpenSSH (Win10 Native)
Git for Windows v2.23.0
Terragrunt v0.19.25
Powershell v5.1.17763.592

**Question(s): Does anyone have any experience getting Terragrunt to work in a Windows environment using SSH? Am I missing something simple? Any advice would be greatly appreciated.**

**Comment by yorinasub17** [comment]
We were able to resolve this with the following setup:

- CMD shell
- Windows 10 Home
- OpenSSH for windows (the one that you can enable in the control panel)
- Git installed via scoop

It started to work once we set `GIT_SSH_COMMAND=C:/WINDOWS/System32/OpenSSH/ssh.exe`. The key issue here was that go expects paths to use `/` instead of `\` even for windows.
