### ISSUE TITLE
Remote state config not detected when using --terragrunt-working-dir

### ISSUE THREAD

**Issue by cpower** [gruntwork-io/terragrunt#95]
**Issue**
When calling terragrunt from the root of directory of project using the `--terragrunt-working-dir` CLI option to reference a sub directory, terragrunt does not see that the remote state is already configure for the S3 backend, and instead runs the `terraform remote config` command.

**Steps to Reproduce**
1. From the root of the project, run `terragrunt apply --terragrunt-workingdir=subdirectory`
2. Run `terragrunt output --terragrunt-working-dir=subdirectory`
Notice that terragrunt still calls `terraform remote config`, even though it was configured by the apply in step 1.
3. Change directory to `subdirectory` and run `terragrunt output`, and notice that terragrunt does not issue the call to `terraform remote config`

**Expected Behavior**
By supplying the `--terragrunt-working-dir` option, terragrunt should notice that the remote state has been configuted by looking in the working dir and not issue that command again

This came up when attempting to use the output from terragrunt as input elsewhere.  Moving terragrunt's output to stderr was very helpful, but the output that results from calling Terraform remote config muddies the waters here.

**Comment by brikis98** [comment]
Definitely a bug. [remote_state.go](https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state.go) is looking for the `.terraform` folder and the state within it in the current working directory rather than the one specified by the `--terragrunt-working-dir` flag (and stored in the `TerragruntOptions` struct). Should be a straightforward fix if anyone is interested in submitting a PR.
