### ISSUE TITLE
Dependency cycle between modules

### ISSUE THREAD

**Issue by leo-viridis** [gruntwork-io/terragrunt#982]
I am aware that dependency cycles end up with an error as stated in #844. However, I have a scenario where I need this to be allowed (or perhaps I am missing something). Here is what I need to achieve.

I have an RDS instance for which I have two security groups. One, `ingress-sg` that allows access to 3306 only from security group `egress-sg`. Security group `egress-sg` on the other hand allows outgoing traffic to port 3306 only towards `ingress-sg` security group. I am using https://github.com/terraform-aws-modules/terraform-aws-security-group to create these two security groups and I use terragrunt to  make this all happen. Setup looks like this:

```sh 
db/
  rds/terragrunt.hcl
  ingress-sg/terragrunt.hcl
  egress-sg/terragrunt.hcl
```
What would be the proper way to go about this using terragrunt since `ingress-sg` and `egress-sg` can't be mutually dependant? Thank you in advance.

**Comment by yorinasub17** [comment]
There is no practical way to allow a dependency cycle because there is no way to prevent and detect an infinite loop where two modules keep affecting each other because the outputs change.

This is a classic SG problem and the way to resolve this is by breaking the cyclic dependency by creating another module (e.g `mutual-sg-rule`) that will create the mutual rules using [the security_group_rule resource](https://www.terraform.io/docs/providers/aws/r/security_group_rule.html).

**Comment by leo-viridis** [comment]
That is exactly what I have setup but I thought there is a single module solution. OK, thank you so much for such a quick response.
