### ISSUE TITLE
[Question] What's the best way to DRY out variables for child modules?

### ISSUE THREAD

**Issue by spark-bo** [gruntwork-io/terragrunt#986]
I'm finding myself duplicating a lot of variables for child module when I use some of the community modules.

For example, I'm trying to use [aws-eks module](https://github.com/terraform-aws-modules/terraform-aws-eks).
As the module requires a few more resources to be created outside of the module, I'm creating a wrapper module and use aws-eks module as a child module.

in parent module:
```
module "eks" {
  source       = "../community_modules/terraform-aws-eks"
  cluster_name = var.cluster_name
  subnets      = var.subnets
  vpc_id       = var.vpc_id
  cluster_version = var.cluster_version
  worker_groups_launch_template = var.worker_groups_launch_template
  config_output_path = var.config_output_path
  cluster_endpoint_private_access = var.cluster_endpoint_private_access
  cluster_endpoint_public_access = var.cluster_endpoint_public_access
}
```

as you can see, I'll be almost repeating the entirety of the variables in the child modules to the parent module. Is there any good way to DRY out the variables in this scenario??

**Comment by yorinasub17** [comment]
Unfortunately, this is a limitation of terraform that terragrunt doesn't have anything to workaround, or intends to solve. Whenever you need to wrap a module and feed forward variables, you are pretty much stuck with duplication.

One alternative is to use a separate module for your dependencies and use [terragrunt output passing](https://terragrunt.gruntwork.io/use-cases/execute-terraform-commands-on-multiple-modules-at-once/#passing-outputs-between-modules) to feed the outputs of the dependencies to the module that needs it, but in this case you will be duplicating the outputs of the dependencies (instead of the vars), so in the end you will still have duplication.
