### ISSUE TITLE
jsondecode in terragrunt.hcl vs an output

### ISSUE THREAD

**Issue by jeffdyke** [gruntwork-io/terragrunt#997]
Hello.  Mainly i'm looking for an official statement, becuase there is a work around.  I'll start with a bare bones file and work into my confusion.
barebones - 
test/terragrunt.hcl
```
include {
  path = find_in_parent_folders()
}

terraform {
  source = "/src/infrastructure/modules//live/test"
}
dependency "security_groups" {
  config_path = "../security_groups"
}

dependency "networking" {
  config_path = "../networking"
}
```

adding `inputs` to the above file, i can not use `jsondecode`
```
inputs = {
  groups = jsondecode(dependency.global.outputs)
  networking = jsondecode(dependency.networking.outputs)
}
```
if i try this i get the error `terragrunt.hcl:14,32-66: Invalid function argument; Invalid value for "str" parameter: string required.`

But i can easily use this in a variables/output.tf with
- replaced from above 
```
inputs = {
  groups = dependency.security_groups.outputs
  networking = dependency.networking.outputs
}
```

Then in variables.tf (being lazy)
```
variable "networking" {
}

variable "groups" {
  type = map(string)
}

output "groups" {
  value = var.groups
}

output "networking" {
  value = {
    subnets = jsondecode(var.networking).subnets
    vpc_id = jsondecode(var.networking).vpc_id
  }
}
```

This works fine, each are decoded and can be used in module, i'm maily curious as to why i get the error when i use them in `inputs`

Thanks for the great software!

**Comment by yorinasub17** [comment]
This is because the type information is lost when bridging from terragrunt to terraform. Within `terragrunt.hcl`, you still have the type information so you have to satisfy those type constraints. This is why you can't pass in `dependency.module.outputs` to `jsondecode`, because the `outputs` attribute is a map type and `jsondecode` uses `string`.

OTOH, when it is passed through to Terraform, Terragrunt uses env vars to pass the variable to terraform (e.g `TF_VAR_varname`). To make this work, Terragrunt will serialize all the data to json and then rely on Terraform to parse out to the right type. So in your example, the `groups` variable has a map type so the json that Terragrunt passes in becomes a map. The `networking` variable, OTOH, has no type info so it defaults to string, and assigns the json as is. Since `var.networking` is a string, you can now use `jsondecode`.

**Comment by jeffdyke** [comment]
@yorinasub17  - Thank you for the detailed response, it is very helpful.  I was not aware of the type information being lost and how to retain it and use it properly in a module.  The need not to call `jsondecode` simply by making

trimmed down databases.hcl (stepped away from my test module)
```
dependency "security_groups" {
  config_path = "../security_groups"
}

inputs = {
  security_groups = dependency.security_groups.outputs
  servers {
    foo {
      groups = "sg_lan_ssh,sg_lan_ping,sg_db_access"
    }
}
```
and then in the module //live/databases i can use (again truncated for simplicity)
variables.tf
```
variable security_groups {
  type = map(string)
}
```
main.tf
```
....
vpc_security_group_ids = [for value in split(",", each.value.groups): var.security_groups[value]]
...
```
Thanks again for the help, if anyone sees anything wrong with the logic above, please note it, otherwise its working like a charm
